### ISSUE TITLE
ImageMarker.addTextByPostion is not working

### ISSUE THREAD

**Issue by kaelsooo** [JimmyDaddy/react-native-image-marker#1]
Good day, thanks for the component and it is very useful.

I am having issues with getting **addTextByPostion** to work on **android**. 
The resulting picture is showing the text on bottom right. 
The position of text is not affected by the change in value of 'position' or 'width' and 'height'.
Have not tested on ios and ImageMarker.addText is working.

Looking forward to your advice thank you.

"react-native": "0.44.2"
"react-native-image-marker": "0.0.5"
"react-native-image-picker": "^0.26.4"

`addTextToPic(path) {

        const uri = path;
        const { title, description, locationName, dateStart } = this.state;
        ImageMarker.addTextByPostion(
            Platform.OS == 'android'? uri.replace('file://', '') : uri,
            title,
            'topLeft',  //position
            100,  //width
            100,  //height
            '#fd5f00',
            'DEFAULT',
            58
        ).then((res) => {   
            this.uploadImageFb(res);
            //console.log("the path is"+res);
        }).catch((err) => {
            console.log(err)
        })  
    }`

![position](https://user-images.githubusercontent.com/29064048/30691251-c15d7102-9ef9-11e7-8902-2f5dd81bf27f.png)

**Comment by JimmyDaddy** [comment]
Sorry for the late response and thanks for committing this issue, I'll check it later and fix it. You can use `addText` instead

**Comment by JimmyDaddy** [comment]
@kaelsooo I fixed this issue 9a3ff82712cf79c5a12d0835b9844d4296c73802

**Comment by kaelsooo** [comment]
thanks jimmydaddy for the great work :D
i have test addtextbyposition and it works well.
