### ISSUE TITLE
markWithImageByPosition is positioning to wrong places

### ISSUE THREAD

**Issue by alperen** [JimmyDaddy/react-native-image-marker#11]
Hello again,

I have a problem with markWithImageByPosition, so thats merge photos to wrong places. If  I would like place to 'topRight', its positioning to topRight near.  One and only topLeft is true. How can i fix this is? or this is bug?

You can check it [here](https://i.hizliresim.com/bBZkd8.png)

**Comment by JimmyDaddy** [comment]
OK. I'll check this and fix it. You can use another API instead

**Comment by JimmyDaddy** [comment]
You can use `markWithImage`  and provide your own `X` and `Y`

**Comment by JimmyDaddy** [comment]
Hello, [0.2.0](https://www.npmjs.com/package/react-native-image-marker) may be fixed this problem, and  there are some [changes](https://github.com/JimmyDaddy/react-native-image-marker#usage) of usage
