### ISSUE TITLE
crash on android 6.0.1

### ISSUE THREAD

**Issue by Zetakai** [JimmyDaddy/react-native-image-marker#116]
**Describe the bug**
crash on marking an image with text then save the image to jpg

**To Reproduce**
```
ImageMarker.markText({
      backgroundImage: {
        src: src,
        scale: 1,
        rotate: 0,
        alpha: 1,
      },
      watermarkTexts: [{
        text: `${this.address}${'\n'}Latitude: ${coordinate.latitude} Longitude: ${coordinate.longitude}${'\n'}${new Date(time.dateTime).toLocaleString()}${'\n'}`,
        positionOptions: {
          position: Position.bottomCenter
        },
        style: {
          color: '#FFFFFF',
          fontSize: 10,
          fontName: 'Arial',
          textBackgroundStyle: {
            paddingX: 10,
            paddingY: 10,
            type: TextBackgroundType.stretchX,
            color: 'transparent',
          },
        },
      }],
      quality: 100,
      filename: 'test',
      saveFormat: ImageFormat.jpg,
      maxSize: 1000
    })
```

**Expected behavior**
no problem on other device but get crash on this particular device

**Screenshots**
<img width="1262" alt="Screenshot 2023-09-05 at 15 06 22" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/32837828/3aeeafa8-4b79-407a-a092-986f6f81fac3">

**Development environment(please complete the following information):**
 - OS: macOS ventura
 - expo: 49.0.8
 - react-native: 0.72.4
 - react-native-image-marker :  1.1.0

**Smartphone (please complete the following information):**
 - Device: OPPO CPH1701
 - OS: android 6.0.1

anyone help please 🥺

**Comment by JimmyDaddy** [comment]
@Zetakai What SDK level are you using? You need API level 24 or above to use it.https://developer.android.com/reference/java/util/concurrent/CompletableFuture
