### ISSUE TITLE
add option in styling for applying border radius in text background

### ISSUE THREAD

**Issue by ubaidimranofficial** [JimmyDaddy/react-native-image-marker#118]
**Is your feature request related to a problem? Please describe.**
For the watermark text background, it can't be able to apply a radius on edges like border-radius.

**Describe the solution you'd like**
need an option to apply radius in styling.

**Describe alternatives you've considered**
n.a
**Additional context**
n.a

**Comment by JimmyDaddy** [comment]
@ubaidimranofficial released at [v1.1.5](https://github.com/JimmyDaddy/react-native-image-marker/releases/tag/v1.1.5)
