### ISSUE TITLE
textAlignment not uniform in android-ios

### ISSUE THREAD

**Issue by sharmaofficial123** [JimmyDaddy/react-native-image-marker#119]
**Describe the bug**
when the position is bottom right ,and the textalign in 'right',it is taking a lot of space in android from the right although it is okay in ios.

**To Reproduce**
Click the image from the camera and apply the textwatermark

**Expected behavior**
the alignment should be uniform

**Screenshots**
ANDROID:
<img width="239" alt="Screenshot 2023-09-19 at 3 10 49 PM" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/69040142/45b8e817-7ce1-4ee2-9f89-ead1e2b31e5e">
IOS:
<img width="273" alt="Screenshot 2023-09-19 at 3 11 01 PM" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/69040142/7af23f7f-2d2b-4210-895c-3ffd39d1b25a">
 **Code**
```
watermarkTexts: [
  {
    text: `${formattedAddress}\n`,
    positionOptions: {
      position: Position.bottomRight
    },
    style: {
      color: '#FF0000',
      fontSize: 6,
      fontName: Fonts.poppinsRegular,
      textAlign: 'right',
      // bold: false,
      textBackgroundStyle: {
        paddingX: 10,
        paddingY: 10,
        color: '#faaaff',
      },
    },
  },
],
```
**Devlopment environment(please complete the following information):**
macOS
react-native-0.68.5

**Smartphone (please complete the following information):**

**Additional context**
@JimmyDaddy

**Comment by JimmyDaddy** [comment]
@sharmaofficial123 fixed in the latest version [1.1.2](https://www.npmjs.com/package/react-native-image-marker/v/1.1.2)
