### ISSUE TITLE
Use bundled image on Android

### ISSUE THREAD

**Issue by egunsoma** [JimmyDaddy/react-native-image-marker#14]
Hi!

Can I use for example the app's icon on Android(`./android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png`) in _markImage_ as **markerSrc**? I couldn't make it work, can somebody help me with this?

**Comment by JimmyDaddy** [comment]
In my opinion,  you don't have to use the icon directly, you can copy the icon to your RN js project and use it as a normal static asset.

**Comment by egunsoma** [comment]
I tried that approach also, without luck, could you help with example code please?
Let's say that the `icon.png` file is in the root of my project, next to `index.js`. How can I tell Android to use this image? I tried:
* simply the **URI** for it: `markerSrc: './icon.png'`
* using **require** like: `markerSrc: require('./icon.png')`
* adding as **Android asset** with `markerSrc: 'asset:/icon.png'`

Thanks @JimmyDaddy for the fast response! 👌

**Comment by JimmyDaddy** [comment]
Hello, I'm sorry for late response, maybe you can try the code below :
```javascript

import { Image } from 'react-native'

Marker.markImage({
        src: this.state.image, 
        markerSrc: Image.resolveAssetSource(require('./icon.jpeg')).uri, 
        position: type, 
        scale: 1, 
        markerScale: 0.5, 
        quality: 100
})
```
**This may only be valid on true device**

**Comment by egunsoma** [comment]
Thank you I will try this out when I get home and update this comment.

**Comment by egunsoma** [comment]
No luck, I get the following error:

**Code**
```javascript
        return Marker.markImage({
          src: Platform.OS == 'android' ? uri.replace('file://', '') : uri,
          // position: 'topLeft',
          X: 20,
          Y: 20, 
          markerSrc: Image.resolveAssetSource(require('../../ic_launcher.png')).uri,
          markerScale: 0.5, 
          scale: 1, 
          quality: 100
        })
      })
```

**Error**
```
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
invoke
    CallbackImpl.java:28
reject
    PromiseImpl.java:68
markWithImage
    ImageMarkerManager.java:343
invoke
    Method.java
invoke
    JavaMethodWrapper.java:372
invoke
    JavaModuleWrapper.java:160
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:192
run
    Thread.java:761

```

This is the same issue as in #12, no solution so far.

**Comment by egunsoma** [comment]
I used [react-native-photo-view](https://github.com/alwx/react-native-photo-view). I rendered my bundled image over the background image and made a view-shot with the linked library.

**Comment by Akkujvl** [comment]
Thanks for your solution but
I think snapshot is not good idea because image quality can be affected

**Comment by JimmyDaddy** [comment]
support yet in the new version [0.3.0](https://www.npmjs.com/package/react-native-image-marker)
