### ISSUE TITLE
Can't put watermark image at specified position on background image.

### ISSUE THREAD

**Issue by ishikawa-takumi** [JimmyDaddy/react-native-image-marker#143]
**Describe the bug**
I want to show water mark image on background image.

I used react-native-image-marker@0.6.3, and It worked fine.
But after updating to 1.1.4, it doesn't work.

My code is this.
```ts
      const url = await Marker.markImage({
        backgroundImage: {
          src: { uri: backgoroundUri }, 
          scale: 1,
        },
        watermarkImages: [
          {
            src: { uri: watermarkImageUri },
            scale: 1,
            position: {
              X: 100,
              Y: 100,
            },
          },
        ],
        quality: 100,
        saveFormat: ImageFormat.jpg,
      });
```

I have checked your code and found the following code to be suspect.
In [react-native-image-marker/android/src/main/java/com/jimmydaddy/imagemarker/base/WatermarkImageOptions.kt](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/android/src/main/java/com/jimmydaddy/imagemarker/base/WatermarkImageOptions.kt) , 
```ts
...
init {
...
    x = if (positionOptions!!.hasKey("X")) positionOptions.getDynamic("X").toString() else null
    y = if (positionOptions.hasKey("Y")) positionOptions.getDynamic("Y").toString() else null
...
}
...
```
Is this code correct??

After I change these codes to
```ts
//add Util.handleDynamicToString()
...
init {
...
    x = if (positionOptions!!.hasKey("X")) Util.handleDynamicToString(positionOptions.getDynamic("X")) else null
    y = if (positionOptions.hasKey("Y")) Util.handleDynamicToString(positionOptions.getDynamic("Y")) else null
...
}
...
```
`Marker.markImage` works fine.

**To Reproduce**

**Expected behavior**
Water mark image is put at specified position on background image.

**Screenshots**

**Devlopment environment(please complete the following information):**
 - OS: macOS
 - nodejs:  18.16.0
 - react-native: 0.72.3
 - react-native-image-marker :  1.1.4

**Smartphone (please complete the following information):**
 - Device: Pixel4
 - OS: Android

**Additional context**

**Comment by JimmyDaddy** [comment]
Hmm, That's probably the reason.

**Comment by ishikawa-takumi** [comment]
@JimmyDaddy 
Thank you for your fix.

**Comment by ishikawa-takumi** [comment]
@JimmyDaddy 
Can you fix iOS code?
It is same problem as Android.

```swift
            self.X = RCTConvert.nsString(positionOpts["X"])
            self.Y = RCTConvert.nsString(positionOpts["Y"])
```
--->
```swift
            self.X = Utils.handleDynamicToString(v: positionOpts["X"])
            self.Y = Utils.handleDynamicToString(v: positionOpts["Y"])
```

**Comment by JimmyDaddy** [comment]
> @JimmyDaddy 
> 
> Can you fix iOS code?
> 
> It is same problem as Android.
> 
> here, [ios/RCTImageMarker/WatermarkImageOptions.swift](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/ios/RCTImageMarker/WatermarkImageOptions.swift)
> 
> ```swift
> 
>             self.X = RCTConvert.nsString(positionOpts["X"])
> 
>             self.Y = RCTConvert.nsString(positionOpts["Y"])
> 
> ```
> 
> --->
> 
> ```swift
> 
>             self.X = Utils.handleDynamicToString(v: positionOpts["X"])
> 
>             self.Y = Utils.handleDynamicToString(v: positionOpts["Y"])
> 
> ```

Sorry for that,I fixed it in the latest version

**Comment by ishikawa-takumi** [comment]
@JimmyDaddy 
Thank you so much!!!
