### ISSUE TITLE
Android sets the text watermark beyond the screen.

### ISSUE THREAD

**Issue by ghost** [JimmyDaddy/react-native-image-marker#151]
<img width="496" alt="image" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/19161230/c5dac32d-3782-4517-8e9e-69ad52927d5b">
<img width="723" alt="image" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/19161230/9c605cb9-419c-4e48-8b35-704bfecd3812">

**Comment by JimmyDaddy** [comment]
可以检查一下：
* 是不是设置的字体大小太大了
* 是不是图片分辨率太低了
