### ISSUE TITLE
android release bug  style not working , debug is ok

### ISSUE THREAD

**Issue by TLB0321** [JimmyDaddy/react-native-image-marker#158]
![image](https://github.com/JimmyDaddy/react-native-image-marker/assets/22816951/ac1bc59f-7802-48a5-8a30-d69a77e2a6d1)

**Comment by TLB0321** [comment]
debug mode
![debug_mode](https://github.com/JimmyDaddy/react-native-image-marker/assets/22816951/0514d50b-0327-4d25-ba9c-2c912303484e)

**Comment by JimmyDaddy** [comment]
@TLB0321 fixed in the latest version [1.1.9](https://www.npmjs.com/package/react-native-image-marker/v/1.1.9)
