### ISSUE TITLE
The 'quality' option not works in latest version(v1.1.8)

### ISSUE THREAD

**Issue by seesawsin** [JimmyDaddy/react-native-image-marker#159]
**Describe the bug**
The 'quality' option does not work, whether set to 0.5 or 50.
But it works well in v0.6.3.

**To Reproduce**
[demo](https://github.com/seesawsin/test-rn-marker)

**Expected behavior**
The 'quality' option should affect to the image size.

**Screenshots**
![v1 1 8-q05](https://github.com/JimmyDaddy/react-native-image-marker/assets/107463723/8ab491a8-1796-49ea-bb0f-7c78918f9028)
![v1 1 8-q50](https://github.com/JimmyDaddy/react-native-image-marker/assets/107463723/2156003e-217d-4425-8eb7-c824395aeeac)
![v0 6 3-q50](https://github.com/JimmyDaddy/react-native-image-marker/assets/107463723/88d94ed4-bf58-4cf4-9bef-908b91c08d00)

**Devlopment environment(please complete the following information):**
 - OS: windows
 - nodejs:  16.19.1
 - react-native: 0.72.7
 - react-native-image-marker :  1.1.8

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: Android 7.1.2

**Comment by JimmyDaddy** [comment]
@seesawsin Hello, does the original image is PNG format? 
PNG is a lossless format, no matter what quality parameter you set, it will not change the image quality.
Maybe you can change the `saveFormat` options to `ImageFormat.jpg` and try again.

**Comment by JimmyDaddy** [comment]
@seesawsin In version 1.1.8, if you don't set the image save format, it will default to PNG format.

**Comment by seesawsin** [comment]
@JimmyDaddy Thanks for your help. After setting the `saveFormat`, the output is as expected.

Additionally, the comments for these two options might be confusing, as their descriptions differ from their actual behavior. Perhaps we should consider making some improvements.
[TextMarkOptions.quality](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/src/index.ts#L600)
[TextMarkOptions.saveFormat](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/src/index.ts#L614)

**Comment by JimmyDaddy** [comment]
> @JimmyDaddy Thanks for your help. After setting the `saveFormat`, the output is as expected.
> 
> Additionally, the comments for these two options might be confusing, as their descriptions differ from their actual behavior. Perhaps we should consider making some improvements. [TextMarkOptions.quality](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/src/index.ts#L600) [TextMarkOptions.saveFormat](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/src/index.ts#L614)

OK, I'll update it ASAP, thank you for this
