### ISSUE TITLE
Fresco 3.1.3 compatibility issues with RN 0.73.0, react-native-image-marker:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by JimmyDaddy** [JimmyDaddy/react-native-image-marker#176]
### Discussed in https://github.com/JimmyDaddy/react-native-image-marker/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **Tiepbm** December 15, 2023</sup>
**Describe the bug**
e: file:///Users/tiepbm/Desktop/TiepBM/PVI/PVI247/node_modules/react-native-image-marker/android/src/main/java/com/jimmydaddy/imagemarker/ImageLoader.kt:140:34 Type mismatch: inferred type is ImagePipelineExperiments but ImagePipelineConfig? was expected
![Uploading image.png…]()

**Devlopment environment(please complete the following information):**
 - OS: Mac M1
 - nodejs:  21.2.0
 - react-native: 0.73.0
 - react-native-image-marker :  1.1.10

**Smartphone (please complete the following information):**
 - Device:SamSung S22
 - OS: Android 12

thanks!
</div>
<div type='discussions-op-text'>

<sup>Originally posted by **JimmyDaddy** December 19, 2023</sup>

I have found the real cause of this problem, [RN <= 0.73.0 uses fresco version is 2.xx.x](https://github.com/facebook/react-native/blob/8cf9505bd27c5dade33b17cc177fa5ef1613dbcd/ReactAndroid/gradle.properties#L15)
[But 0.73.0 uses 3.1.3](https://github.com/facebook/react-native/blob/43826facfab8eed7d01a801778d1c477e60730a6/packages/react-native/gradle/libs.versions.toml#L19C1-L19C1).
It seems ImagePipelineConfig.newBuilder(context).experiment().setMaxBitmapSize(int).build() return ImagePipelineExperiments instead of ImagePipelineConfig now.
Sorry for that, I'll update a fix ASAP to adapt the 0.73.x
</div>

**Comment by Tiepbm** [comment]
@JimmyDaddy Can I ask when will you release the new version?
thanks,

**Comment by JimmyDaddy** [comment]
> @JimmyDaddy Can I ask when will you release the new version? thanks,

@Tiepbm 
I'll release a minor version, 1.2.0, after I fixed #179

**Comment by Tiepbm** [comment]
> > @JimmyDaddy Can I ask when will you release the new version? thanks,
> 
> @Tiepbm I'll release a minor version, 1.2.0, after I fixed #179 today

thanks!
