### ISSUE TITLE
Same watermark image is behaving differently on ANDROID and IOS when use given position enum

### ISSUE THREAD

**Issue by EducoreAPK** [JimmyDaddy/react-native-image-marker#179]
**Describe the bug**
When i am adding a watermark image on Android it is working perfectly as expected.
But when working on IOS the watermark image is losing its original aspect ratio and its getting very blurry.

**To Reproduce**
```
              Marker.markImage({
                    backgroundImage: {
                        src: IMAGEURL,
                        scale: 1,
                    },
                    watermarkImages: [{
                        src: wIMAGEURL,
                        position: {
                            position: Position.bottomLeft,
                        },
                        scale: 0.1,
                        // alpha: 1
                    }],
                    scale: 1,
                    quality: 100,
                }).then((path) => {
                    resolve(path)
                }).catch((error) => {
                    resolve(false)
                })
```

**Expected behavior**
IMAGE SHOULD BE SAME ON BOTH ANDROID AND IOS

I m using  CameraRoll library to download image afterwards
 CameraRoll.save(dPath, { type: 'photo', album: 'EducoreParent' }).then((res) => {
                        console.log('res', res);
                    }).catch((error) => {
                        console.log('error', error);
                    })

**Screenshots**
<img width="975" alt="image" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/126555658/421b561f-d562-43f4-8133-b7325112db8f">

**Devlopment environment(please complete the following information):**
 - OS: MacOS 14.2 (23C64)
 - nodejs:  v18.18.0
 - react-native: 0.72.7
 - react-native-image-marker :  "^1.1.9"

**Smartphone (please complete the following information):**
 - Device: IOS 13ProMax  - OS: IOS 17.0
 -  - Device: Pixel 6  - OS: Android 13

**Comment by JimmyDaddy** [comment]
@EducoreAPK v1.1.11 is available

**Comment by JimmyDaddy** [comment]
@EducoreAPK You can try [1.2.1](https://www.npmjs.com/package/react-native-image-marker/v/1.2.1)
