### ISSUE TITLE
Img doesnt display on built APK

### ISSUE THREAD

**Issue by Eqls** [JimmyDaddy/react-native-image-marker#18]
When I build a signed APK the image stops displaying, works fine while just running in emulator though.

**Comment by JimmyDaddy** [comment]
Hello, can you show me more details? For example, the code that you use this plugin.

**Comment by Eqls** [comment]
Hi, thanks for a quick response! Works perfectly while im using an emulator, but once i build a signed APK the img just doesnt load

```
  putWaterMarkOnImage = uri => {
    Marker.markImage({
      src: uri,
      markerSrc: LogoWhiteImg,
      // topLeft, topCenter,topRight, bottomLeft, bottomCenter , bottomRight, center
      X: 0,
      Y: 0,
      scale: 1,
      markerScale: 0.05,
      quality: 100
    })
      .then(path => {
        console.log(Platform.OS === 'android' ? 'file://' + path : path)
        this.setState({
          uri: Platform.OS === 'android' ? 'file://' + path : path,
          loading: false
        })
      })
      .catch(err => {
        console.log(err, 'err')
        this.setState({
          loading: false,
          err
        })
      })
  }
```

**Comment by JimmyDaddy** [comment]
@Eqls I fixed this bug, you can try [the new version](https://www.npmjs.com/package/react-native-image-marker).

**Comment by Eqls** [comment]
Thank you! But I have another problem which results in the same outcome, it happens when I try to change the scaling now. Error message: framesToPop: 1, code: error. I have a github repo available for my app if you are interested in checking it out! Called fliparoo. Appreciate your time!

**Comment by JimmyDaddy** [comment]
@Eqls I didn't reproduce this issue on both true device and simulator, can you tell me how to reproduce it?

There is my code:
```javascript
// src/screens/Photo.js
Marker.markImage({
      src: uri,
      markerSrc: LogoWhiteImg,
      // topLeft, topCenter,topRight, bottomLeft, bottomCenter , bottomRight, center
      X: 0,
      Y: 0,
      scale: 2,
      markerScale: 6, // I changed the marker's scale and it works fine.
      quality: 100
    })

```
By the way, you should avoid changing the background's scale to 2 or more times big, it will cause OOM  on an Android device when the original image was a big one.

***I published a new version to optimize OOM problem.***

**Comment by Eqls** [comment]
@JimmyDaddy first of all thank you! But if I set markerScale to 1 then it just get the same problem - it doesnt display the image, if i scale to lets just say 2 it work, but then it looks ugly and its not at the correct cooridnate: i set coordinates 0 0 and it displays around the middle too.

**Comment by JimmyDaddy** [comment]
@Eqls I'm sorry for this bug, It's a cache problem, I fixed it in [the latest version (0.3.4)](https://www.npmjs.com/package/react-native-image-marker).

**Comment by Eqls** [comment]
@JimmyDaddy I love you. Thanks!

**Comment by JimmyDaddy** [comment]
@Eqls You are welcome.

**Comment by dvxdxm** [comment]
@JimmyDaddy  i same issue problem. Not show text on device .This is my code.
makerImage(uri,time) {
    
     if(uri) {
       ImageMarker.markText({
         src: uri.replace('file://',''),
         text: time,
         color: '#FF0000',
         fontName: 'Arial-BoldItalicMT', 
         fontSize: 30, 
         position:'bottomCenter',
         scale: 1, 
         quality: 100
      }).then((res) => {
        this.setState({
          uri: Platform.OS === 'android' ? 'file://' + res : res
        });
          this.props.navigation.navigate('Dashboard',
          {
            data: this.state.uri,
            lat:this.state.makerPosition.latitude,
            long:this.state.makerPosition.longitude,
            isTake:true
          });
         //console.log("the path is"+res)
      }).catch((err) => {
         console.log(err)
      });
     }
  }

**Comment by JimmyDaddy** [comment]
@dvxdxm are you using the latest version?

**Comment by dvxdxm** [comment]
> @dvxdxm are you using the latest version?

i updated lastest version.that's working.Thank u @JimmyDaddy
