### ISSUE TITLE
Crash on ios when running markText

### ISSUE THREAD

**Issue by dheeraj-jft** [JimmyDaddy/react-native-image-marker#184]
**Describe the bug**
Crash on ios when running markText

<img width="1440" alt="Screenshot 2023-12-27 at 9 13 01 PM" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/92309468/7f282e65-73d5-4e37-a024-36dd2950b15a">

I am using sample code from readme.

import Marker, {
  ImageFormat,
  Position,
  TextBackgroundType,
} from 'react-native-image-marker';
export const AddTextToImage = (path, text) => {
  const options = {
    // background image
    backgroundImage: {
      src: require('../../../assets/images/Avatar.jpg'),
      scale: 1,
    },
    watermarkTexts: [
      {
        text: text,
        positionOptions: {
          position: Position.topLeft,
        },
        style: {
          color: '#ff00ff',
          fontSize: 30,
          fontName: 'Arial',
          shadowStyle: {
            dx: 10,
            dy: 10,
            radius: 10,
            color: '#008F6D',
          },
          textBackgroundStyle: {
            padding: '10% 10%',
            type: TextBackgroundType.none,
            color: '#0FFF00',
          },
        },
      },
    ],
    scale: 1,
    quality: 100,
    filename: 'test',
    saveFormat: ImageFormat.png,
  };
  Marker.markText(options);
};

**Comment by dheeraj-jft** [comment]
I removed the code related to color, but now I got another error. 
<img width="1440" alt="Screenshot 2023-12-28 at 7 19 35 AM" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/92309468/0525413f-18bd-4870-b3cc-332cb00b9969">

Please let me know what I am missing here. @JimmyDaddy

**Comment by JimmyDaddy** [comment]
@dheeraj-jft does `../../../assets/images/Avatar.jpg` exists in your project?

**Comment by JimmyDaddy** [comment]
@dheeraj-jft [1.2.1](https://www.npmjs.com/package/react-native-image-marker/v/1.2.1) is available

**Comment by dheeraj-jft** [comment]
Thanks, it worked.
