### ISSUE TITLE
> Yes, It is 8.0.1. Should I upgrade it?

### ISSUE THREAD

**Issue by dheeraj-jft** [JimmyDaddy/react-native-image-marker#188]
> Yes, It is 8.0.1. Should I upgrade it?

Yes, [`Coil` ](https://github.com/coil-kt/coil) need gradle 8.0.3. [You can refer to the Gradle version settings in the example project](https://github.com/JimmyDaddy/react-native-image-marker/blob/69f58f79c98626e8102b30cec277e34d2937a002/example/android/gradle/wrapper/gradle-wrapper.properties#L3C5-L3C5).

_Originally posted by @JimmyDaddy in https://github.com/JimmyDaddy/react-native-image-marker/issues/183#issuecomment-1870260351_
            

I am getting this error while upgrading to gradle 8.3. 
/.gradle/wrapper/dists/gradle-8.3-bin/dxjbbhstwasg8cbags9q7cvli/gradle-8.3/lib/kotlin-stdlib-1.9.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

Did you mention gradle 8.0.3 or 8.3

**Comment by JimmyDaddy** [comment]
@dheeraj-jft what the `kotlin_version` is in your project? And what is your `react-native` version?

**Comment by dheeraj-jft** [comment]
![Screenshot from 2023-12-29 08-23-38](https://github.com/JimmyDaddy/react-native-image-marker/assets/92309468/ddd0aafa-a304-4fd6-b0ae-c59ef8f37033)
![Screenshot from 2023-12-29 08-19-36](https://github.com/JimmyDaddy/react-native-image-marker/assets/92309468/1fabb0b7-c2cd-488d-bf1b-a0fc275d9e6a)

**Comment by dheeraj-jft** [comment]
![image](https://github.com/JimmyDaddy/react-native-image-marker/assets/92309468/10cceaa0-123a-491e-9e94-c3084d48cbcf)

**Comment by JimmyDaddy** [comment]
@dheeraj-jft `react-native@0.72.x` is not compatible with 1.2.x, your should use 1.1.x or upgrade your react-native to 0.73.x.
[doc here](https://github.com/JimmyDaddy/react-native-image-marker?tab=readme-ov-file#compatibility)

**Comment by dheeraj-jft** [comment]
I have completely removed the library still I am getting this error on android. The same code with the latest version 1.2.1 worked on ios.

**Comment by JimmyDaddy** [comment]
> I have completely removed the library still I am getting this error on android. The same code with the latest version 1.2.1 worked on ios.

This is caused by a conflict between the Kotlin version used by Gradle 8.3 and the Kotlin version used by react-native@0.72.x. If you want to keep the react native version unchanged and run normally on Android, you also need to downgrade the Gradle version to 8.0.x.

**Comment by JimmyDaddy** [comment]
You need to gradle clean and rebuild
