### ISSUE TITLE
Cannot read property 'markWithImage' of undefined. 

### ISSUE THREAD

**Issue by alfiyabohra** [JimmyDaddy/react-native-image-marker#19]
Please help me resolve this. I have installed latest version of image marker

**Comment by lgngnr** [comment]
i have the same issue... running react-native link log nothing

**Comment by JimmyDaddy** [comment]
@lgngnr it may be the module didn't installed correctly.
* On Android, 
you should check `{yourRNProject}/android/settings.gradle`, there may be:

```gradle
include ':react-native-image-marker'
project(':react-native-image-marker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-marker/android')
```
if you installed this module correctly.

* On iOS, 
you should open this project with XCode and check the `Libraries` folder, there may be:
![e17203ce-b3ed-4384-a7be-7f2722ae01e3](https://user-images.githubusercontent.com/16460813/52924752-02055f80-3369-11e9-8d1b-b1c9ce6a3e4c.png)
if you installed this module correctly.

And also DO NOT forget link this module to the project:
![4a397b1e-9523-4414-acd4-f013e79ba3c0](https://user-images.githubusercontent.com/16460813/52924816-514b9000-3369-11e9-808c-14eb32408332.png)

**Comment by lgngnr** [comment]
1)i run npm i --save react-native-image-marker then react-native link react-native-image-marker
2) check {yourRNProject}/android/settings.gradle  => It's ok
3) check {yourRNProject}/android/app/build.gradle => it's ok

Now i have the following: 
undefined is not an object (evaluating 'ImageMarker.markWithImageByPosition')
markImage

**Comment by JimmyDaddy** [comment]
@lgngnr if you want to use `markWithImageByPosition`, you should do the following:
```javascript
import { NativeModules } from 'react-native'
const { ImageMarker } = NativeModules

// Arguments are not an object, and they should be spread
ImageMarker.markWithImageByPosition(
        srcObj, // background image
        markerObj, // marker
        position, 
        scale,
        markerScale,
        quality,
        filename // saved name
)
```
***I DO SUGGEST you use this module by following***
```javascript

import ImageMarker from "react-native-image-marker"

Marker.markImage({
    src: backGroundUri, 
    markerSrc: iconUri, 
    position: 'topLeft',  // topLeft, topCenter,topRight, bottomLeft, bottomCenter , bottomRight, center
    scale: 1, 
    markerScale: 0.5, 
    quality: 100
}).then((path) => {
    this.setState({
        uri: Platform.OS === 'android' ? 'file://' + path : path,
        loading: false
    })
}).catch((err) => {
    console.log(err, 'err')
     this.setState({
        loading: false,
        err
    })
})
```
or you can learn it from [README](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/README.MD) or [Example](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/example/markerExample/App.js)

**Comment by JimmyDaddy** [comment]
By the way, on Android there may be
```java
 @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ImageMarkerPackage()  // this is how the Marker be imported to the NativeMoudles 
      );
    }
```
if you installed this moudle correctly.

**Comment by lgngnr** [comment]
ok, sorry but if i declare the import as 
import ImageMarker from "react-native-image-marker"

then call Marker.whateveri get an rerror cant't variable Marker but if i do

import Marker from "react-native-image-marker"

this error: undefined is not an object (evaluating 'ImageMarker.markWithImageByPosition') 
is raised when i call
Marker.markImage({
    src: backGroundUri, 
    markerSrc: iconUri, 
    position: 'topLeft',  // topLeft, topCenter,topRight, bottomLeft, bottomCenter , bottomRight, center
    scale: 1, 
    markerScale: 0.5, 
    quality: 100
}).then((path) => {
    this.setState({
        uri: Platform.OS === 'android' ? 'file://' + path : path,
        loading: false
    })
}).catch((err) => {
    console.log(err, 'err')
     this.setState({
        loading: false,
        err
    })
})

We miss something

**Comment by lgngnr** [comment]
i try even 
```javascript
Marker.markText({
                        src: photo.uri,
                        text: 'text marker',
                        X: 100, // left
                        Y: 150, // top
                        color: '#FF0000',
                        fontName: 'Arial-BoldItalicMT',
                        fontSize: 44,
                        scale: 1,
                        quality: 100
                    }).then((path) => {
                        console.log(path)
                        this.setState({
                            photo: {
                                uri: Platform.OS === 'android' ? 'file://' + path : path,
                            },
                            showCamera: false,
                            showImageViewer: true,
                            loading: false,
                        })
                    }).catch((err) => {
                        console.log(err, 'err')
                        this.setState({
                            loading: false,
                        })
                    })
```
and similar error

```
undefined is not an object (evaluating 'ImageMarker.addText')
markText
    index.js:88:25
onPictureSaved
    Toolbar.js:77:36
_onPictureSaved
    Camera.js:202:15
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:93:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:318:36
invokeGuardedCallbackAndCatchFirstError
    ReactNativeRenderer-dev.js:342:30
executeDispatch
    ReactNativeRenderer-dev.js:715:42
executeDispatchesInOrder
    ReactNativeRenderer-dev.js:737:20
executeDispatchesAndRelease
    ReactNativeRenderer-dev.js:894:29
forEachAccumulated
    ReactNativeRenderer-dev.js:876:12
runEventsInBatch
    ReactNativeRenderer-dev.js:1050:21
runExtractedEventsInBatch
    ReactNativeRenderer-dev.js:1072:19
<unknown>
    ReactNativeRenderer-dev.js:2707:6
batchedUpdates$1
    ReactNativeRenderer-dev.js:17297:14
batchedUpdates
    ReactNativeRenderer-dev.js:2610:31
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2705:17
receiveEvent
    ReactNativeRenderer-dev.js:2725:26
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
```

**Comment by JimmyDaddy** [comment]
Is there 
```java
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ImageMarkerPackage()  // this is how the Marker be imported to the NativeMoudles 
      );
    }
```
in `MainApplication.java`

**Comment by lgngnr** [comment]
yes

```java
import com.jimmydaddy.imagemarker.ImageMarkerPackage;
...
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ImageMarkerPackage(),
            new RNShimmerPackage(),
      );
    }
```

**Comment by JimmyDaddy** [comment]
It is very strange, could you tell me the RN version  of your project?

**Comment by lgngnr** [comment]
"react-native": "^0.57.7",

**Comment by lgngnr** [comment]
Meanwhile try to build android with ./gradlew assembleRelease
```
Execution failed for task ':react-native-image-marker:verifyReleaseResources'
```

**Comment by JimmyDaddy** [comment]
@lgngnr I think there may be something wrong with your project's android config,  there is a [exapmle](https://github.com/JimmyDaddy/makerExample) with RN version `0.57.7`, I've test it on my PC, you can compare it to your project to find the difference.

**Comment by JimmyDaddy** [comment]
BTW, you can open your project with [Android Studio](https://developer.android.com/studio/), this IDE can help you to fix some typical problems on Android config

**Comment by JimmyDaddy** [comment]
run `./gradlew  assembleRelease --stacktrace `
![6425d93e-1d3f-4b01-b046-91393ea0ffc4](https://user-images.githubusercontent.com/16460813/53065379-5bef5c00-3506-11e9-9b2c-a07b2e6f7e1b.png)

run `react-native run-android`
![dd42a70f-a01f-48f9-93e1-12297f38245e](https://user-images.githubusercontent.com/16460813/53065438-a1ac2480-3506-11e9-8e50-d64c2ef1249e.png)

run on simulator result
![e398c6cc-9bcd-4982-93fc-99bf8f4ca296](https://user-images.githubusercontent.com/16460813/53065482-cd2f0f00-3506-11e9-8ed8-c2ac811a3167.png)

**Comment by lgngnr** [comment]
I clone your repo and it works
I create a brand new project with react-native init install your npm package, link it and it work
I create a brand new project with expo init install your npm package and not work because can't link the module so use expo eject to link the module and doesn't work... the problem is expo... i'll try to make run it with expo if you have any suggestion let me know

**Comment by JimmyDaddy** [comment]
@lgngnr There is a [Expo ejected example](https://github.com/JimmyDaddy/markerExpoExample)

**Comment by lgngnr** [comment]
i try it, same error ImageMarker.markWithImage undefnied...

How do you create the project?

expo init [managed, advanced]
expo eject [ReactNative, ExpoKit]

**Comment by lgngnr** [comment]
Hi, i make it!

I write here the procedure i do, can be helpful to anyone maybe can go to the readme

1) Create a new project with **expo init** 
2) Run **expo eject** and choose **expoKit** so can i have both react-native and expo api
3) Run it with **expo start**
4) Install **npm i --save react-native-image-marker**
5) Link dependencies **react-native link react-native-image-marker**
6) Meanwhile **expo start** still running open the android project with android studio end run it or just from command line  **cd android** and **./gradlew installDevKernelDebug**, it'll build the apk and install and run it on the device/emulator connected through adb. If doesn't run automatically just open app drawer and open the installed apk

Just work, thank you for your previous support

**Comment by JimmyDaddy** [comment]
@lgngnr You are welcome.

**Comment by diarynar** [comment]
hello, can we interact with the clicked marker? for example if we click on a marker, we get a popup that appears.
