### ISSUE TITLE
 Marker.markText option is not visible 

### ISSUE THREAD

**Issue by karthikkarunanithi91** [JimmyDaddy/react-native-image-marker#192]
I used    "react-native-image-marker": "^1.1.11",

              "react-native": "0.71.3",
![Uploading WhatsApp Image 2024-01-09 at 9.22.50 AM.jpeg…]()

**Comment by karthikkarunanithi91** [comment]
My source code is 

   const options = {
    // background image
    backgroundImage: {
      src: require('../../assets/Image/abtr_centralOffice.png'),
      scale: 1,
    },
    watermarkTexts: [{
      text: 'hellow',
      positionOptions: {
        position: Position.topLeft,
      },
      style: {
        color: '#ff00ff',
        fontSize: 30,
        fontName: 'Arial',
        shadowStyle: {
          dx: 10,
          dy: 10,
          radius: 10,
          color: '#008F6D',
        },
        textBackgroundStyle: {
          padding: '10% 10%',
          type: TextBackgroundType.none,
          color: '#0FFF00',
        },
      },
    }],
    scale: 1,
    quality: 100,
    filename: 'test',
    saveFormat: ImageFormat.png,
  };
  Marker.markText(options);

**Comment by JimmyDaddy** [comment]
@karthikkarunanithi91 The image didn't upload successfully. Did you mean that the watermark on the image was invisible?

**Comment by JimmyDaddy** [comment]
I have tried with your code, but it got correct result 
```ts
const options = {
  // background image
  backgroundImage: {
    src: require('./bg.png'),
    scale: 1,
  },
  watermarkTexts: [
    {
      text: 'hellow',
      positionOptions: {
        position: Position.topLeft,
      },
      style: {
        color: '#ff00ff',
        fontSize: 30,
        fontName: 'Arial',
        shadowStyle: {
          dx: 10,
          dy: 10,
          radius: 10,
          color: '#008F6D',
        },
        textBackgroundStyle: {
          padding: '10% 10%',
          type: TextBackgroundType.none,
          color: '#0FFF00',
        },
      },
    },
  ],
  scale: 1,
  quality: 100,
  filename: 'test',
  saveFormat: ImageFormat.png,
};
const path = await Marker.markText(options);

```
<img width="347" alt="截屏2024-01-09 23 18 37" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/16460813/6c1bedae-935e-4793-9ad8-730535c0c42d">
