### ISSUE TITLE
fontName not work (ANDROID)

### ISSUE THREAD

**Issue by vioku** [JimmyDaddy/react-native-image-marker#195]
` const options = {
        backgroundImage: {
          src: response.assets[0].uri,
          scale: 1,
        },
        watermarkTexts: [
          {
            text: 'hello-' + Date.now(),
            positionOptions: {
              position: Position.center,
            },
            style: {
              color: '#ff00ff',
              fontSize: 30,
              fontName: 'OoohBaby-Regular',

              textBackgroundStyle: {
                type: TextBackgroundType.none,
              },
            },
          },
        ],
        scale: 1,
        quality: 100,

        saveFormat: ImageFormat.png,
      };
      Marker.markText(options)
        .then(res => {
          setimage('file://' + res);
        })
        .catch(err => {
          console.log(err);
        }); `
Whats wrong ? custom font not work

i have tested on <Text> my font show correctly
`<Text className="text-white font-[OoohBaby-Regular] text-3xl text-center">
        Testing Font
      </Text>`

![Screenshot 2024-01-22 110545](https://github.com/JimmyDaddy/react-native-image-marker/assets/88869626/c671eee7-729b-4fd8-9137-713a7f08e6bd)

**Comment by JimmyDaddy** [comment]
@vioku Can you submit a PR for this fix? 😊

**Comment by vioku** [comment]
> @vioku Can you submit a PR for this fix? 😊

Done Sir @JimmyDaddy 😊💥
