### ISSUE TITLE
API 28 Canvas Issue

### ISSUE THREAD

**Issue by ishwartolanij** [JimmyDaddy/react-native-image-marker#20]
Hi ,
Updated to API 28 .
It does not build anymore.
ImageMarkerManager.java:294: error: method save in class Canvas cannot be applied to given types;
canvas.save(Canvas.ALL_SAVE_FLAG);
               
Canvas.save(int) has been removed from API 28. In was deprecated since 28, now it is fully removed and you should call Canvas.save() instead .

Thanks

**Comment by JimmyDaddy** [comment]
Hi, @ishwartolanij this issue has been fixed in the latest version.

**Comment by ishwartolanij** [comment]
Hi @JimmyDaddy ,
Thanks for quick fix .

But In android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.java
Line 219 also uses canvas.save(Canvas.ALL_SAVE_FLAG);

Please check the same .

**Comment by AArvesh16** [comment]
@ishwartolanji thanks for giving this 
as my error is been solved
