### ISSUE TITLE
High resolution image is rotated on ios after watermark

### ISSUE THREAD

**Issue by StanislavMayorov** [JimmyDaddy/react-native-image-marker#201]
Hello! Thank you for the library.

**Describe the bug**
High resolution `markText backgroundImage` image 3024 × 4032 (from iphone XR camera, HEIC/jpg) is rotated after applying watermarkTexts. 605 × 806 image works okay. 

**To Reproduce**
1. Use ios device
2. Use example [image](https://github.com/JimmyDaddy/react-native-image-marker/files/14029026/input.jpeg.zip) and code below
```
Marker.markText({
    backgroundImage: {
        src: image.uri,
        scale: 1,
    },
    watermarkTexts: [
        {
            text: 'test',
            positionOptions: {
                position: Position.center,
            },
            style: {
                color: '#ffffff80',
                fontSize: 40,
                textBackgroundStyle: {
                    color: '#F4A1A154',
                },
                textAlign: 'left',
            },
        },
    ],
    filename: image.name,
    saveFormat: ImageFormat.jpg,
})
```
Result: photo is rotated.
![result copy](https://github.com/JimmyDaddy/react-native-image-marker/assets/11670429/d154d390-7b81-4a75-a3bf-2e9a40c889b4)

**Expected behavior**
Watermark applied and photo not rotated

**Development environment:**
 - OS: macos 13.6.3
 - nodejs:  16.14.0
 - react-native: 0.71.6
 - react-native-image-marker :  1.1.11/1.2.3 tested

**Smartphone :**
 - Device: iPhone XR
 - OS: ios 16

**Comment by JimmyDaddy** [comment]
@StanislavMayorov Sorry, I didn't repreduce this issue by your code and image, there is my test result: 
```ts
const uri = await Marker.markText({
        backgroundImage: {
          src: require('./yahaha.jpeg'),
          scale: 1,
        },
        watermarkTexts: [
          {
            text: 'test',
            positionOptions: {
              position: Position.center,
            },
            style: {
              color: '#ffffff80',
              fontSize: 40,
              textBackgroundStyle: {
                color: '#F4A1A154',
              },
              textAlign: 'left',
            },
          },
        ],
        filename: image.name,
        saveFormat: ImageFormat.jpg,
      })
```
![9A4460C1-D748-4722-88AA-E7003A645DCA](https://github.com/JimmyDaddy/react-native-image-marker/assets/16460813/d459855e-ea6b-49d6-8381-4356ac656e47)

You can test it with [the example project
](https://github.com/JimmyDaddy/react-native-image-marker/tree/master/example)

**Comment by StanislavMayorov** [comment]
I can't reproduce the issue. I tried the latest and my versions of libs in the example project and I removed `launchImageLibrary maxWidth: 2000, maxHeight: 2000`.
I can reproduce it only in my app when `file://` path from `react-native-image-picker` is used . I logged urls and checked files in the file system in my app. Image is rotated just after Marker.markText.
```
    "react-native-image-marker": "1.1.11",
    "react-native-image-picker": "3.3.2",
```
So it's something wrong on my side. Thank you!

**Comment by qq382724935** [comment]
iphone xs Encountering the same problem。

**Comment by qq382724935** [comment]
` Marker.markText({
            quality: options.quality,
            backgroundImage: {
              src: data.uri,
              scale: 1,
            },
            watermarkTexts: [
              {
                text: watermark,
                positionOptions: {
                  position: Position.center,
                },
                style: {
                  color: '#FF0000',
                  fontName: 'Arial-BoldItalicMT',
                  fontSize: 88,
                  shadowStyle: {
                    dx: 0,
                    dy: 0,
                    radius: 0,
                    color: '#0000FF',
                  },
                  textBackgroundStyle: {
                    type: TextBackgroundType.stretchX,
                    paddingX: 0,
                    paddingY: 0,
                    color: '',
                  },
                },
              },
            ],
          }).then((image) => this.fileDataChange(`file:///${image}`));`

**Comment by qq382724935** [comment]
Marker.markText({
            quality: options.quality,
            backgroundImage: {
              src: data.uri,
              scale: 1,
            },
            watermarkTexts: [
              {
                text: watermark,
                positionOptions: {
                  position: Position.center,
                },
                style: {
                  color: '#FF0000',
                  fontName: 'Arial-BoldItalicMT',
                  fontSize: 88,
                  shadowStyle: {
                    dx: 0,
                    dy: 0,
                    radius: 0,
                    color: '#0000FF',
                  },
                  textBackgroundStyle: {
                    type: TextBackgroundType.stretchX,
                    paddingX: 0,
                    paddingY: 0,
                    color: '',
                  },
                },
              },
            ],
          }).then((image) => this.fileDataChange(`file:///${image}`));

**Comment by qq382724935** [comment]
version 1.1.15
RN version 0.71.14

**Comment by qq382724935** [comment]
Marker.markText({
            quality: options.quality,
            backgroundImage: {
              src: data.uri,
              scale: 1,
            },
            watermarkTexts: [
              {
                text: watermark,
                positionOptions: {
                  position: Position.center,
                },
                style: {
                  color: '#FF0000',
                  fontName: 'Arial-BoldItalicMT',
                  fontSize: 88,
                  shadowStyle: {
                    dx: 0,
                    dy: 0,
                    radius: 0,
                    color: '#0000FF',
                  },
                  textBackgroundStyle: {
                    type: TextBackgroundType.stretchX,
                    paddingX: 0,
                    paddingY: 0,
                    color: '',
                  },
                },
              },
            ],
          }).then((image) => this.fileDataChange(`file:///${image}`));
