### ISSUE TITLE
Generates inconsistent text size across different devices

### ISSUE THREAD

**Issue by eljubec** [JimmyDaddy/react-native-image-marker#202]
**Describe the bug**
When generating images with text in them, the size of the text changes depending on what phone you use. I tried generating the **same** image with text on two different phones - an _iPhone SE (3rd Generation)_ and an _iPhone 15 Pro Max_. The text turned out to be much bigger on the _iPhone 15 Pro Max_ than on the _iPhone SE_ which is strange, especially considering that the same parameters were used for generating the images.

**To Reproduce**

Following code was used on both devices to generate the images shown below:

```
const image = await ImageMarker.markText({
    saveFormat: ImageFormat.jpg,
    backgroundImage: {
        src: 'https://images.unsplash.com/photo-1434281406913-47acccb03654?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzMTA3Nzl8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MDYwOTU2ODl8&ixlib=rb-4.0.3&q=80&w=1080',
        scale: 1,
    },
    watermarkTexts: [
        {
            text: 'Duis aute irure dolor in reprehenderit\n in voluptate velit esse cillum valum',
            positionOptions: {
                position: Position.center,
            },
            style: {
                color: '#fbfbfb',
                fontName: 'Arial-BoldMT',
                fontSize: 24,
                shadowStyle: {
                    dx: 3,
                    dy: 3,
                    radius: 6,
                    color: '#0000004f'
                },
                textAlign: 'left',
            }
        }
    ]
});

await MediaLibrary.saveToLibraryAsync(image);
```

**Expected behavior**
In this case, I have set specific parameters for how the text should appear on the image, so the result should be consistent/identical regardless which devices was used to generate the image.

**Screenshots**
iPhone 15 Pro Max
![iPhone 15 Pro Max](https://github.com/JimmyDaddy/react-native-image-marker/assets/36228716/784e1efb-d98f-40ac-af99-3395302e38c0)

iPhone SE 3rd Gen
![iPhone SE 3gen](https://github.com/JimmyDaddy/react-native-image-marker/assets/36228716/ebd6cabc-c210-4f9b-b3ae-65da869f8373)

**Devlopment environment:**
 - react-native: 0.72.6
 - react-native-image-marker :  1.2.3

**Smartphone:**
 - Simulators: iPhone SE 3rd gen, iPhone 15 Pro Max
 - OS: iOS 17.0.1

**Comment by JimmyDaddy** [comment]
Thank you for reporting this issue, I have found the cause of the issue and will fix it shortly.

**Comment by JimmyDaddy** [comment]
[v1.2.4](https://www.npmjs.com/package/react-native-image-marker/v/1.2.4) is available

**Comment by pramahaditamaputra** [comment]
Hi @JimmyDaddy how to solve this issue for project react native 0.72.x ? in OS Android 14 the text size come more bigger
i try to upgrade to v1.2.6 but its give me new error like this https://github.com/JimmyDaddy/react-native-image-marker/issues/183
