### ISSUE TITLE
API 28 Build Failed Issue

### ISSUE THREAD

**Issue by ishwartolanij** [JimmyDaddy/react-native-image-marker#21]
Thanks for quick fix .

But In android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.java
Line 219 also uses canvas.save(Canvas.ALL_SAVE_FLAG);

Please check the same .

_Originally posted by @ishwartolanij in https://github.com/JimmyDaddy/react-native-image-marker/issues/20#issuecomment-446943334_

**Comment by JimmyDaddy** [comment]
😅I'm sorry, fixed 742141034cb2bc380c0f31c209584254a064c202
