### ISSUE TITLE
Expo project build failed with react-native-image-marker

### ISSUE THREAD

**Issue by StrangeTown** [JimmyDaddy/react-native-image-marker#213]
An error occurred when I run "expo run:android" in Expo project: "FAILURE: Build failed with an exception."

<img width="1253" alt="image" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/8406419/7c86004f-080d-4fd7-9c5e-aae99068254e">

1. I installed the react-native-image-marker first
```
npx expo install react-native-image-marker
```

2. Then, I ran prebuild
```
npx expo prebuild -p android
```

3. I got the error when I tried to run the project
```
yarn run android
```

### Environment
"react-native": "0.72.6",
"react-native-image-marker": "^1.2.5",
node version: v18.17.0
Gradle 8.0.1

**Comment by JimmyDaddy** [comment]
@StrangeTown Hello, according the RN and Gradle version your project used, you should use v1.1.5, [ref](https://github.com/JimmyDaddy/react-native-image-marker?tab=readme-ov-file#compatibility)

**Comment by StrangeTown** [comment]
Thank you so much for replying

My project run successfully after I changed the version to v1.1.5 as you mentioned.
