### ISSUE TITLE
The X and Y of watermarkImages not work

### ISSUE THREAD

**Issue by StrangeTown** [JimmyDaddy/react-native-image-marker#215]
<img width="719" alt="image" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/8406419/eeff46db-f022-4bca-a5bd-0aee72be0e70">

I have set the Y of watermarkImage's position, but the image was still on the top of the background image.

**Comment by JimmyDaddy** [comment]
@StrangeTown hello, can you update to v[1.1.15](https://www.npmjs.com/package/react-native-image-marker/v/1.1.15) and try again? I made a mistake in the version number in [my previous issue response](https://github.com/JimmyDaddy/react-native-image-marker/issues/213#issuecomment-1915943055). It should be 1.1.15, not 1.1.5.

**Comment by StrangeTown** [comment]
The position worked when I update the version to v1.1.15. Thank you!!
