### ISSUE TITLE
1.1.15 version had some issues in Android build 

### ISSUE THREAD

**Issue by MarwadTech** [JimmyDaddy/react-native-image-marker#224]
**Describe the bug**
while creating Android build showing error 

**To Reproduce**
1. Go to 'normal run the android app (yarn android)'
2. Click on 'build failed'
3. Scroll down to 'nothing'
4. See error = Could not determine the dependencies of task ':react-native-image-marker:compileDebugAidl'.
> Problems reading data from Binary store in /Users/bhanwarsuthar/.gradle/.tmp/gradle336922897664867668.bin offset 1065525 exists? true

**Expected behavior**
successfully create android build 

**Screenshots**
<img width="1025" alt="Screenshot 2024-04-01 at 3 49 18 PM" src="https://github.com/JimmyDaddy/react-native-image-marker/assets/50322392/fdf0807a-4050-42cc-8756-5e069c1709d6">

**Devlopment environment(please complete the following information):**
 - OS: [e.g. OSX/windows]
 - nodejs:  [e.g. 18.19.1]
 - react-native: [e.g. 0.72.5]
 - react-native-image-marker :  [e.g. 1.1.15]

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - OS: [e.g. Android 13]

**Comment by wublack** [comment]
me too!

**Comment by JimmyDaddy** [comment]
@wublack @MarwadTech what is the gradle version your project use

**Comment by MarwadTech** [comment]
@JimmyDaddy 
Gradle Version 

{
        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlin_version = "1.8.0"
        kotlinVersion = "1.8.0"
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "25.1.8937393"
        androidXAnnotation = "1.2.0"
        androidXBrowser = "1.3.0"
    }

**Comment by IamHungry113** [comment]
any update ?
I have same problem here

**Comment by AlexMuhammad** [comment]
@JimmyDaddy is there solution for this issue, i just got this problem when i rebuilt my project, and i got build failed.

**Comment by JimmyDaddy** [comment]
https://github.com/JimmyDaddy/react-native-image-marker/discussions/185

https://github.com/JimmyDaddy/react-native-image-marker/issues/188

Guys, you need to update your gradle to 8.3

**Comment by Flano-123** [comment]
> #185
> 
> #188
> 
> Guys, you need to update your gradle to 8.3

I got the same problem and update the gradle version to 8.3 doesn't work for me. It will raise another new problem:

\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\utils\TaskUtils.kt: (27, 12): Class 'kotl
in.collections.ArraysKt___ArraysKt' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.

**Comment by huynextlevel** [comment]
Hi @JimmyDaddy ,

I got the same error. I also followed commetn #185 #183 . The issue still happen, current my version information:
React Native: v0.72.10
react native image marker: v1.1.15
grandle: v8.0.1 (I tried with 8.3 still not working)

**Comment by shubhadeep29** [comment]
same problem. any update?

**Comment by lucasgbsampaio** [comment]
Guys, check the library version in the yarn.lock/package-lock.json. Should be exactly 1.1.15

**Comment by shubhadeep29** [comment]
The error is gone after switching the version to 1.1.15. 

Thanks @lucasgbsampaio

**Comment by pramahaditamaputra** [comment]
Hi @shubhadeep29 do you face any problem in android 14 ? the font size come more bigger ?
