### ISSUE TITLE
(Android) Cannot read the file from the path 

### ISSUE THREAD

**Issue by dcanora** [JimmyDaddy/react-native-image-marker#23]
Hello! Having trouble getting this working. Have tried different images - sourced from camera, image picker and the expo/react-native assets directory, but markImage cannot retrieve any file.  Any help is greatly appreciated. Thanks and Happy New Year! 

`[Error: Can't retrieve the file from the path: file:///data/user/0/com.myapp.demo/cache/ExperienceData/%2540dcanora%252FProjectA/Camera/8aed441a-3524-4b0f-9b87-de9be5b52d87.jpg]`

_By the way, my app is an ejected Expo app. Linking worked fine and android build had no issues._

**Comment by JimmyDaddy** [comment]
Hello, @dcanora, sorry for the late reply. I fixed this bug in [the latest version](https://www.npmjs.com/package/react-native-image-marker)
Thanks for using this module.
 
And Happy New Year!

**Comment by dcanora** [comment]
Hello and Happy New Year @JimmyDaddy!  Thanks for the quick fix, but I think there may still be a bug. The `path` returned is malformed with a double extension (.jpg):
 
`/data/user/0/com.myapp.demo/cache/fda7f9c7-915b-4485-a632-452eb7d6b34aimagemarkermyphoto.jpg.jpg`

I assume `imagemarker` is added for uniqueness. May I suggest the following formatting:

`/data/user/0/com.myapp.demo/cache/fda7f9c7-915b-4485-a632-452eb7d6b34a-imagemarker-myphoto.jpg`

(Do I need to put this in a new issue?)

Thanks for providing this module... Cheers!

**Comment by JimmyDaddy** [comment]
Thanks for your good suggestion @dcanora

Yes, you'd better open a new Feature request issue, I'll work on it when I'm available.

**Comment by vivekshah-zymr** [comment]
@JimmyDaddy ,Android:  I am not able to get the file on the path, I am using the latest npm version 0.5.0

**Comment by JimmyDaddy** [comment]
@vivekshah-zymr Can you show me your code?

**Comment by vivekshah-zymr** [comment]
@JimmyDaddy , Here's the code.
```
let markedImage = await ImageMarker.markImage({
                    src: bgImg,
                    markerSrc: newImage,
                    position: 'topCenter',
                    scale: 1,
                    markerScale: 1,
                    quality: 100
                });
                markedImage = (Platform.OS === 'android') ? 'file://' + markedImage : markedImage
                console.log("markedImage", markedImage)
                let finalImage = await ImageMarker.markImage({
                    src: markedImage,
                    markerSrc: result.pathName,
                    position: 'bottomCenter',
                    scale: 1,
                    markerScale: 0.25,
                    quality: 100
                });
                finalImage = (Platform.OS === 'android') ? 'file://' + finalImage : finalImage
                const base64String = await ImgToBase64.getBase64String(finalImage);
                await this.uploadImageS3(base64String);
            }
```

**Comment by srichallamalla935** [comment]
@JimmyDaddy,
Android: I am not able to get the file on the path, I am using the latest npm version "^0.6.1",
My path looks like " data/data/com.sampleproject/cache/727b3cdc-2ff1-4918-8a71-f00be535e4d9imagemarker.png"
The cache folder is blank

**Comment by srichallamalla935** [comment]
@vivekshah-zymr Did u got solution for blank image in cache in android?Please help me out
