### ISSUE TITLE
"markImage" makes output bigger in resolution

### ISSUE THREAD

**Issue by rendomnet** [JimmyDaddy/react-native-image-marker#25]
**Describe the bug**
"res"  after markImage is different size then original image and using markImage again on it results is incorrect  

**To Reproduce**
```
    ImageMarker.markImage({
      src: res,
      markerSrc: require("/img/start2.png"),
      position: "bottomLeft", 
      scale: 1,
      markerScale: 1,
      quality: 100
    }).then(res => {
      ImageMarker.markImage({
        src: "http://" + res,
        markerSrc: require("/img/start2.png"),
        position: "bottomLeft", 
        scale: 1,
        markerScale: 1,
        quality: 100
      }).then(res => ....)
    })

```

second image is a lot smaller but they should be exactly the same 

**Expected behavior**
Same image size

**Screenshots**
![image](https://user-images.githubusercontent.com/18900210/52402930-b55f9000-2aef-11e9-8fff-69da2c8e4485.png)

**Devlopment environment(please complete the following information):**
 - OS: OSX
 - nodejs:  8.9.1
 - react-native: 0.57.8
 - react-native-image-marker :  0.3.9

**Smartphone (please complete the following information):**
 - Device:/Simulator
 - OS: iOS11

**Additional context**
markText do not have this bug

**Comment by JimmyDaddy** [comment]
@rendomnet The latest version fixed this bug.
