### ISSUE TITLE
rn 0.58.4 android build issue

### ISSUE THREAD

**Issue by nonotest** [JimmyDaddy/react-native-image-marker#26]
**Describe the bug**
Getting build errors because of promise.reject on rn 58.4

**To Reproduce**
Create a new project with rn 58.4, `./graddlew assembleRelease`

**Expected behavior**
App builds

===

It seems that something changed with react promise.reject signature;

```
reference to reject is ambiguous
                promise.reject( "error","Can't retrieve the file from the path.",null);
```

For each call site that has string,string as params, removing the second string works
For each call site that has string,string,throwable as params, removing the middle string works

might not be the best solution.. !

**Comment by JimmyDaddy** [comment]
@nonotest The latest version fixed this bug.

**Comment by nonotest** [comment]
thanks
