### ISSUE TITLE
Android: markText can't use local image

### ISSUE THREAD

**Issue by rendomnet** [JimmyDaddy/react-native-image-marker#27]
**Describe the bug**
Can't use local image on android for source when using markText

**To Reproduce**
```
      lmageMarker.markText({
        src: require("../imgs/img1.jpg"),
        text: "12345",
        X: 0,
        Y: 0,
        color: "white,
        fontName: "Arial-BoldMT",
        fontSize: 36,
        scale: 1,
        quality: 20
      });
```
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18900210/52547158-a6c6f080-2def-11e9-9500-c20508c78a1e.png)

**Devlopment environment(please complete the following information):**
 - OS: OSX
 - nodejs:  [e.g. 8.9.0]
 - react-native: [e.g. 0.57.8]
 - react-native-image-marker :  0.4

**Smartphone (please complete the following information):**
 - Device: Simulator

**Additional context**

**Comment by JimmyDaddy** [comment]
@rendomnet 0.41 supported this feature.
