### ISSUE TITLE
Android: markImage can't use base64 as marker.

### ISSUE THREAD

**Issue by rendomnet** [JimmyDaddy/react-native-image-marker#28]
**Describe the bug**
on Android i cant use base64 string as marker

Gives error:
Error: Can't get resource by the path: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAADwCAYAAAA+VemSAAAABHNCSVQICAgIfAhkiAAABV1JREF

On iOS it is working.

**To Reproduce**

```
marked = await ImageMarker.markImage({
        src: "file",
        markerSrc: { uri:  "data:image/png;base64,iVBORw...},
        X: 800,
        Y: 715,
        scale: 1,
        markerScale: 1,
        quality: 20
      });
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18900210/52583454-dca0bf00-2e59-11e9-8dc7-ad47a83278e9.png)

**Devlopment environment(please complete the following information):**
 - OS: OSX
 - nodejs:  [e.g. 8.9.0]
 - react-native: 0.57.8
 - react-native-image-marker :  0.41

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: Android

**Additional context**

**Comment by JimmyDaddy** [comment]
@rendomnet Thanks for reporting this, the latest version(0.4.2) supported this feature already

**Comment by rendomnet** [comment]
Still cant use base64 

Error: Can't get resource by the path: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAADwCAYAAAA+VemSAAAABHNCSVQICAgIfAhkiAAABCJJREFU
eJzt3bGO2zoURdFJkP//5aRwaU1BaMjcba1VPuAZGsUbbA7ory8AAAB4hl8X/+3v8afou3qP3/nk
9+s97PX2fn//j6cAfoaAIUzAECZgCBMwhAkYwgQMYQKGMAFDmIAh7M/N/39lOlczYeq3a5pYmzz6
nn3DCQxhAoYwAUOYgCFMwBAmYAgTMIQJGMIEDGEChrC7U8oVJnl77frbau/sUd8zJzCECRjCBAxh
AoYwAUOYgCFMwBAmYAgTMIQJGMJOTilZ96hZIOucwBAmYAgTMIQJGMIEDGEChjABQ5iAIUzAECZg
CDOlPK82Tdz1w+H8ACcwhAkYwgQMYQKGMAFDmIAhTMAQJmAIEzCECRjCTk4pzexedt00ufJ+P3ke
WXveW5zAECZgCBMwhAkYwgQMYQKGMAFDmIAhTMAQJmAIuzulnPAD1J9swjxywuzS9+wbTmAIEzCE
CRjCBAxhAoYwAUOYgCFMwBAmYAgTMIQ96ga/oNqE0PfpMCcwhAkYwgQMYQKGMAFDmIAhTMAQJmAI
EzCECRjCrm6lnPAD1CsmzA0nTAhrN02umHDj5gRvf5sTGMIEDGEChjABQ5iAIUzAECZgCBMwhAkY
wgQMYVdTStO59c/dZcIz1N7ZBMfegxMYwgQMYQKGMAFDmIAhTMAQJmAIEzCECRjCBAxhd2+l/OTp
3IT3MOHWxNrfNmGGu+LW8zqBIUzAECZgCBMwhAkYwgQMYQKGMAFDmIAhTMAQdvJWygmzwBW19zBh
1jrhb1t5htrs8o0TGMIEDGEChjABQ5iAIUzAECZgCBMwhAkYwgQMYVfzMJPHl9ossPYMKybMRHdx
KyU8lYAhTMAQJmAIEzCECRjCBAxhAoYwAUOYgCHs5K2UNbWJJnuN/HdzAkOYgCFMwBAmYAgTMIQJ
GMIEDGEChjABQ5iAIexqSjlyMjbcyuzSRPNlwmR31w9873qGN05gCBMwhAkYwgQMYQKGMAFDmIAh
TMAQJmAIEzCEXU0pV0yYw+2ya5q4a7434Ue7J8wNJ3wnjz2vExjCBAxhAoYwAUOYgCFMwBAmYAgT
MIQJGMIEDGF3p5QrJtyaOGFmVzNhHrnrcyfMT289rxMYwgQMYQKGMAFDmIAhTMAQJmAIEzCECRjC
BAxhJ6eUvOya702YPE64RbP2ubc4gSFMwBAmYAgTMIQJGMIEDGEChjABQ5iAIUzAEGZKOduE+d6E
iWbtc4/dfuoEhjABQ5iAIUzAECZgCBMwhAkYwgQMYQKGMAFD2MkppR/Xfplwy+MuE+acE26aPDa7
dAJDmIAhTMAQJmAIEzCECRjCBAxhAoYwAUOYgCHs7pTy2A8ZP1RtmjjBhEnpiluzSycwhAkYwgQM
YQKGMAFDmIAhTMAQJmAIEzCECRgAAAAAgH3+AX23T/W4sK+rAAAAAElFTkSuQmCC

**Comment by JimmyDaddy** [comment]
@rendomnet Fixed this in the latest version. It was a base64 string match problem

**Comment by jacky-ew** [comment]
Hi @JimmyDaddy  is the conversion of base64 will only return in png?

**Comment by JimmyDaddy** [comment]
@jacky-ew you can set `saveFormat`
