### ISSUE TITLE
imgSavePath error

### ISSUE THREAD

**Issue by raghunathmestry** [JimmyDaddy/react-native-image-marker#30]
I have getting {"framesToPop":1,"code":"imgSavePath error"} 

and my code is 

import ImageMarker from "react-native-image-marker";
ImageMarker.markImage({
            src: this.state.imageData.ImagePath, 
            markerSrc: this.state.icon, // icon uri
            X: this.state.iconx, // left
            Y: this.state.icony, // top
            scale: 1, // scale of bg
            markerScale: 0.5, // scale of icon
            quality: 100 // quality of image
        }).then((path) => {
            console.warn(path);
            this.setState({
                loading: false
            })
        }).catch((err) => {
            console.warn(err)
            this.setState({
                loading: false
            })
        })

**Comment by JimmyDaddy** [comment]
@raghunathmestry What's the `this.state.imageData`? And what's the `this.state.imageData.ImagePath`?
