### ISSUE TITLE
Uri cache problem

### ISSUE THREAD

**Issue by onka13** [JimmyDaddy/react-native-image-marker#35]
I can't get expected final image when using markText twice or more with same filename.

`Marker.markText({
	src: this.uri,
	filename: "test",
}).then(path => {
     // /data/user/0/com.test213/cache/test.jpg
	Marker.markText({
		src: "file://" + path,
		filename: "test",
	}).then(path => {
		
	})
})`

I've search about the problem. This can be related with caching. 

[https://frescolib.org/docs/image-requests.html](https://frescolib.org/docs/image-requests.html)

Finally If I use version parameter on second call its working. 
`src: "file://" + path + "?v=" + new Date().getTime()`

You can add a caching option or add an info about caching on first page.

**Comment by JimmyDaddy** [comment]
This may be the RN's image cache, the final image should be processed success.
