### ISSUE TITLE
Text quality very poor

### ISSUE THREAD

**Issue by nohaapav** [JimmyDaddy/react-native-image-marker#37]
**Describe the bug**
Text quality very poor

<img width="636" alt="Screen Shot 2019-03-17 at 5 06 26 PM" src="https://user-images.githubusercontent.com/4179104/54494117-45ef7400-48d7-11e9-99bc-72098e15e2c3.png">

Anything i can do about that ? Bg image is 640x640

**To Reproduce**
1. Call markText with following options:

```
Marker.markText({
    src: <some-bg-image>,
    text: <some-text>, 
    position: 'center', 
    color: '#ffffff',
    fontName: 'Avenir-Roman', 
    fontSize: 20, 
    scale: 1, 
    quality: 100
}).then((res) => {
    console.log(res)
}).catch((err) => {
    console.log(err)
})
```

**Devlopment environment(please complete the following information):**
 - OS: OSX
 - nodejs:  8.11.3
 - react-native: 0.55.4
 - react-native-image-marker :  0.4.4

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: iOS 12.1

**Comment by Udbhav12** [comment]
@JimmyDaddy - How to define a generic font size  in markText method which will work for all android phones?

Example - If I use font size 40, the text is very small in Samsung Galaxy A10 device, but in Redmi Note 4A device ,the same font size of 40 is appropriate

**Comment by egulhan** [comment]
> @JimmyDaddy - How to define a generic font size in markText method which will work for all android phones?
> 
> Example - If I use font size 40, the text is very small in Samsung Galaxy A10 device, but in Redmi Note 4A device ,the same font size of 40 is appropriate

yes, I have same problem like above. still not fixed or any workaround solution for that?

**Comment by NeerajNema1988** [comment]
@JimmyDaddy  - How to define the generic font size in markText method which will work for all android phones?

**Comment by NeerajNema1988** [comment]
> @JimmyDaddy - How to define a generic font size in markText method which will work for all android phones?
> 
> Example - If I use font size 40, the text is very small in Samsung Galaxy A10 device, but in Redmi Note 4A device ,the same font size of 40 is appropriate

@egulhan - Did you find out the solution for this?

**Comment by NeerajNema1988** [comment]
> @JimmyDaddy - How to define a generic font size in markText method which will work for all android phones?
> 
> Example - If I use font size 40, the text is very small in Samsung Galaxy A10 device, but in Redmi Note 4A device ,the same font size of 40 is appropriate

@Udbhav12 - Are you able to solve this issue?
