### ISSUE TITLE
null is not an object (evaluating 'imageMarker.addTextByPostion') 

### ISSUE THREAD

**Issue by joeljerushan** [JimmyDaddy/react-native-image-marker#39]
Can you help me to find what i was doing wrong here.. im getting following error `null is not an object (evaluating 'imageMarker.addTextByPostion') `
my function code follows 

```
        Marker.markText({
            src: this.state.imageurl,
            text: 'text marker', 
            position: 'topLeft', 
            color: '#FF0000',
            fontName: 'Arial-BoldItalicMT', 
            fontSize: 44, 
            mShadowStyle: {
                dx: 10.5,
                dy: 20.8,
                radius: 20.9,
                color: '#ff00ff'
            },
            scale: 1, 
            quality: 100,
            filename: 'hello_oii'
        }).then((res) => {
            this.setState({
                uri : 'SET URL'
            })
        }).catch((err) => {
            console.log(err)
            this.setState({
                uri : 'UNSET URL',
                err
            })
        })
```

![image](https://user-images.githubusercontent.com/10111309/57586275-32483e80-7511-11e9-92d1-0b8790148e93.png)
(below screenshot)

**Comment by JimmyDaddy** [comment]
@joeljerushan Did you run `react-native link react-native-image-marker`?

**Comment by joeljerushan** [comment]
@JimmyDaddy i have done it by Manual Linking, `react-native link react-native-image-marker` this not working for `iOs`. so Problem Solved for me.

is there any way to align Text only Vertically and fixed number for Horizontally ? Text should start from center check attached screenshot. when i use `bottomCenter` text showing from center that is fine but i wanted to align it to fixed Horizontally and centered Vertical Text Placement. by doing this my text will appear inside green highlighted box 

![image](https://user-images.githubusercontent.com/10111309/57610668-e6d47580-758e-11e9-9970-beac97efb2c2.png)

**Comment by weiliang903** [comment]
same error for me.
```
"react-native": "0.61.1",
"react-native-image-marker": "^0.6.1",
```
<img width="377" alt="屏幕快照 2019-11-04 19 08 58" src="https://user-images.githubusercontent.com/20644345/68116788-9aaf3000-ff36-11e9-8657-03915f4b2a17.png">

**Comment by weiliang903** [comment]
resolved. Thanks
```
watchman watch-del-all
rm -rf node_modules
```
