### ISSUE TITLE
How to add mutilple image marker on same source?

### ISSUE THREAD

**Issue by usmankhan495** [JimmyDaddy/react-native-image-marker#40]
Hi 
Thanks for awesome library. Can you please help me to add multiple images (or text) on same image source using x and y points.
Thanks

**Comment by onka13** [comment]
Hi @usmankhan495, check this;
[https://github.com/JimmyDaddy/react-native-image-marker/issues/35](https://github.com/JimmyDaddy/react-native-image-marker/issues/35)

```
markFunc().then(path => {
  markFunc().then(path2 => {
    markFunc().then(path3 => {
      ....
    })
  })
})
```
