### ISSUE TITLE
ImageMarker.addText got 14 arguments, expected 13

### ISSUE THREAD

**Issue by EleeMosinarY** [JimmyDaddy/react-native-image-marker#41]
i am getting this "ImageMarker.addText got 14 arguments, expected 13"  when i am trying to add text on image.
and unable to add text on image

Marker.markText({
          src: uri,
          text: "Watermark",
          X: 300,
          Y: 1110,
          color: "#e9e9e9",
          fontName: 'Montserrat-Light',
          fontSize: 80,
          shadowStyle: {
            dx: 10.5,
            dy: 20.8,
            radius: 20.9,
            color: "#e9e9e9"
          },
          scale: 1,
          quality: 100
        })

**Comment by JimmyDaddy** [comment]
@EleeMosinarY Sorry for getting back to you so late. It seems like you are using the source code of github directly, [js code](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/index.js) is the latest, but the native code (java or ObjectC) is not.

**Comment by JimmyDaddy** [comment]
Maybe you can remove this module from node_modules of your project and run `npm install react-native-image-marker@latest` to solve this
