### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by cjinghong** [JimmyDaddy/react-native-image-marker#43]
**Describe the bug**
Trying to apply watermark fails.

**To Reproduce**
Apply watermark with the following options.
```
ImageMarker.markImage({
    src: { uri: `data:image/png;base64,${base64ImageString}` },
    // markerSrc: assets.watermark, // digi watermark from assets.
    markerSrc: assets.watermark,
    scale: 1, // scale of bg
    markerScale: 1, // scale of icon
    quality: 100 // quality of image
  })
```
I've tried changing src to a static image, changing markerSrc to a base64 string, using image uri, and none of it works. The base64 string is verified to be correct (I pasted the string into a converter and it returns an image).

I also did `react-native-link` already.

**Expected behavior**
return a path as result

**Devlopment environment(please complete the following information):**
 - OS: OSX
 - nodejs:  8.12.0
 - react-native: 0.59.6
 - react-native-image-marker :  0.5.0

**Comment by JimmyDaddy** [comment]
@cjinghong There are no default options for `position ` or `X/Y`, you should set `position` or `X/Y`

**Comment by JimmyDaddy** [comment]
* [position](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/example/markerExample/App.js#L230)
* [X/Y](https://github.com/JimmyDaddy/react-native-image-marker/blob/master/example/markerExample/App.js#L292)
