### ISSUE TITLE
Can we arrange two image on side of each other and create a new image?

### ISSUE THREAD

**Issue by vivekshah-zymr** [JimmyDaddy/react-native-image-marker#44]
**Is your feature request related to a problem? Please describe.**
I am developing a project where I have requirement like user uploads the 2 picture from gallary and we have to upload it over the S3. So can we do this by using this library?

**Describe the solution you'd like**
Can we arrange selected two pictures side by side and merge them? As we want 1st one on top and second one at bottom of the 1st one.

**Describe alternatives you've considered**
Suggest me any alternative to achive this.

**Comment by JimmyDaddy** [comment]
@vivekshah-zymr this looks like an image/photo editor library, maybe you can try [this](https://github.com/prscX/react-native-photo-editor).

**Comment by vivekshah-zymr** [comment]
@JimmyDaddy , Let me put my exact requirement. I am having a requirment where user do a signature on a canvas and then click a picture from the camera. And I need to merge this sign and the clicked image and send it to the backend API without displaying merged image to user. 
I don't know if your suggested lib work or not for this.

**Comment by JimmyDaddy** [comment]
Did you mean merging the signature to the picture side by side, not marking the signature to the picture and use it as background?

**Comment by vivekshah-zymr** [comment]
I mean side by side and not marking the sign to the picture. attached pic for ref.
<img width="419" alt="Screen Shot 2019-07-16 at 12 22 02 PM" src="https://user-images.githubusercontent.com/26891421/61272483-e5a90a00-a7c4-11e9-80be-e23a0e701948.png">

**Comment by JimmyDaddy** [comment]
This could be a temporary solution:
```javascript
import React from 'react';
import Marker from 'react-native-image-marker';

const BlankBg = require('./assets/blankBg.png')

const mergeExample = async () => {
  // using a blank image as background, make the photo fill half of it
  const markedImage = await Marker.markImage({
    src: BlankBg,
    markerSrc: 'photo from gallary',
    ...imageOptions
  });
  // then adding the signature to the merged image
  const res = Marker.markText({
    src: markedImage,
    text: 'signature',
    ...textOptions
  })
  
  upload(res)
}


```

**Comment by vivekshah-zymr** [comment]
@JimmyDaddy , Thanks. It worked well.
