### ISSUE TITLE
When I add watermarks to multiple images， Can't retrieve the file from the path

### ISSUE THREAD

**Issue by NMding** [JimmyDaddy/react-native-image-marker#45]

**Comment by NMding** [comment]
_addWaterMarker = ({path, width}) => {

        return new Promise( async (resolve) => {

            let ratio = width / WINDOW_WIDTH / 2
            let markerUri = await this.waterMarkerRef.capture()
            let markerUri2 = await this.waterMarkerRef2.capture()

            let newPath = await Marker.markImage({
                src: path, 
                markerSrc: markerUri,
                // X: width / 25, // left
                // Y: width / 25, // top
                position: 'topLeft',
                scale: 1, // scale of bg
                markerScale: ratio, // scale of icon
                quality: 100 // quality of image
            })

            let finalPath = await Marker.markImage({
                src: IS_IOS ? newPath : 'file://' + newPath, 
                markerSrc: markerUri2,
                position: 'bottomLeft',
                scale: 1, // scale of bg
                markerScale: ratio, // scale of icon
                quality: 100 // quality of image
            })

            resolve(IS_IOS ? finalPath : 'file://' + finalPath)
        })
    }

**Comment by JimmyDaddy** [comment]
@NMding 
```js
 Platform.OS === 'android' ? 'file://' + path : path
```
