### ISSUE TITLE
Does not read rotation info in EXIF-data

### ISSUE THREAD

**Issue by mikaello** [JimmyDaddy/react-native-image-marker#5]
Some cameras (e.g. Samsung-phones) does not rotate picture when taken in other direction than landscape (the "correct" way), but rather include information about rotation in EXIF-information.

This module does not read EXIF data, so pictures with rotation data will loose this data and picture will not get rotated:

![mark](https://user-images.githubusercontent.com/2505178/32835439-68f9fc0a-ca06-11e7-81c3-e601d6e8e955.jpg)

Suggested fix:
Read EXIF-data and rotate picture accordingly before adding text and creating new bitmap (which will discard the original EXIF-information)

**Comment by JimmyDaddy** [comment]
Ok, thanks for your suggestion. I'll fix it as soon as I can

**Comment by JimmyDaddy** [comment]
Hello, [0.2.0](https://www.npmjs.com/package/react-native-image-marker) may be fixed this problem, and  there are some [changes](https://github.com/JimmyDaddy/react-native-image-marker#usage) of usage
