### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by BaderSerhan** [JimmyDaddy/react-native-image-marker#51]
Does this library have video support, i.e. can we add pictures and text as markers to videos? If no, do you plan to support that?

Thanks in advance, and love your work!

**Comment by JimmyDaddy** [comment]
@BaderSerhan thank you for using this library.  I'll support video watermarking in the future.

**Comment by wsdt** [comment]
Would be amazing!

**Comment by Kuhne1** [comment]
@JimmyDaddy Great to hear, Do you have any timeframe on implementation?

**Comment by WowJesse** [comment]
@JimmyDaddy Look forward to new video features, look forward to!

**Comment by ManigandanRaamanathan** [comment]
@JimmyDaddy any update on this?

**Comment by ShivamJoker** [comment]
Another library maybe ?

**Comment by JimmyDaddy** [comment]
https://github.com/arthenica/ffmpeg-kit/blob/main/react-native/README.md
