### ISSUE TITLE
Updated Image is Not saved on Android device

### ISSUE THREAD

**Issue by EricCheung3** [JimmyDaddy/react-native-image-marker#52]
**Describe the bug**
I downloaded the example, and played with it on my android device, which I try to add some text, after adding text on the selected image using those buttons, I found the origin selected image was saved instead of new updated image. (save to other functions)

What am I doing wrong? 
Or how can I save the updated image to my device (I tried react-native-fs which I didn't make it  work....)?

**To Reproduce**
1. Go to the app
2. Click on `switch to mark text`
3. Click `pick image`
4. Click `mark`
5. Go to photos to check the downloaded image which is the original image

**Expected behavior**
the updated image should be saved.

**Devlopment environment(please complete the following information):**
 - OS: [Windows]
 - nodejs:  v10.16.3
 - react-native: 0.60.5
 - react-native-image-marker :  0.5.1

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [Android 9.0]

Thanks for your help.

**Comment by JimmyDaddy** [comment]
@EricCheung3  这里是不会修改原图片的，所以你需要将返回的图片地址指向的图片拷贝到你想保存的地方去， BTW，中文没问题吧。
https://github.com/JimmyDaddy/react-native-image-marker#save-image-to-file

**Comment by EricCheung3** [comment]
谢谢， 我用了react-native-fs，但是报httpurlconnnection error； 我改用CameraRoll之后可以保存成功:https://github.com/react-native-community/react-native-cameraroll
