### ISSUE TITLE
react-native-image-marker:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by gusma296** [JimmyDaddy/react-native-image-marker#55]
when i generate release apk, i found this error : 

> Task :react-native-image-marker:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-marker:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2741: error: resource android:attr/fontStyle not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2742: error: resource android:attr/font not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2743: error: resource android:attr/fontWeight not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2744: error: resource android:attr/fontVariationSettings not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2745: error: resource android:attr/ttcIndex not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2909: error: resource android:attr/startX not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2912: error: resource android:attr/startY not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2915: error: resource android:attr/endX not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2918: error: resource android:attr/endY not found.
  /Users/gusma/Documents/Gusma/yoayo-mobile-app/node_modules/react-native-image-marker/android/build/intermediates/res/merged/release/values/values.xml:2926: error: resource android:attr/offset not found.
  error: failed linking references.

how to fix this error ? please help me

Devlopment environment(please complete the following information):

OS : OSX
react-native : 0.61.2
nodejs v10.16.3
react-native-image-marker : 0.6.0

**Comment by ahmadf27** [comment]
yeah I got this issue to brad

**Comment by gusma296** [comment]
anyone can help for fix this error

**Comment by Baterka** [comment]
Same error! I can't build Release version! Debug version works fine

**Comment by onka13** [comment]
I didn't test but could you please try to change "node_modules/react-native-image-marker/android/build.gradle" like this;

```
apply plugin: 'com.android.library'

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet("compileSdkVersion", 23)
    buildToolsVersion safeExtGet("buildToolsVersion", '23.0.1')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 22)
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    api 'com.facebook.react:react-native:+'
}
```

**Comment by Baterka** [comment]
Problem is 100% bad SDK version (23) but I am not sure why its working on debug build

**Comment by Baterka** [comment]
> I didn't test but could you please try to change "node_modules/react-native-image-marker/android/build.gradle" like this;
> 
> ```
> apply plugin: 'com.android.library'
> 
> def safeExtGet(prop, fallback) {
>     rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
> }
> 
> android {
>     compileSdkVersion safeExtGet("compileSdkVersion", 23)
>     buildToolsVersion safeExtGet("buildToolsVersion", '23.0.1')
> 
>     defaultConfig {
>         minSdkVersion safeExtGet('minSdkVersion', 16)
>         targetSdkVersion safeExtGet('targetSdkVersion', 22)
>         versionCode 1
>         versionName "1.0"
> 
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
> 
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     testCompile 'junit:junit:4.12'
>     api 'com.facebook.react:react-native:+'
> }
> ```

This is working. So problem is in Sdk Version :)

**Comment by Baterka** [comment]
@JimmyDaddy Can you update repo please?

**Comment by gusma296** [comment]
> I didn't test but could you please try to change "node_modules/react-native-image-marker/android/build.gradle" like this;
> 
> ```
> apply plugin: 'com.android.library'
> 
> def safeExtGet(prop, fallback) {
>     rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
> }
> 
> android {
>     compileSdkVersion safeExtGet("compileSdkVersion", 23)
>     buildToolsVersion safeExtGet("buildToolsVersion", '23.0.1')
> 
>     defaultConfig {
>         minSdkVersion safeExtGet('minSdkVersion', 16)
>         targetSdkVersion safeExtGet('targetSdkVersion', 22)
>         versionCode 1
>         versionName "1.0"
> 
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
> 
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     testCompile 'junit:junit:4.12'
>     api 'com.facebook.react:react-native:+'
> }
> ```

this is not work for me

**Comment by JimmyDaddy** [comment]
Sorry for the late response. I updated it [v0.6.1](https://www.npmjs.com/package/react-native-image-marker)

**Comment by gusma296** [comment]
thanks @JimmyDaddy

**Comment by arifinoid** [comment]
thanks @JimmyDaddy @onka13 it's worked for me 👍
