### ISSUE TITLE
Gradle obsolete configuration

### ISSUE THREAD

**Issue by bvidalTMM** [JimmyDaddy/react-native-image-marker#57]
Hello,

The module use a deprecated gradle configuration, and generate a warning when apk was generated : 

> Configure project :react-native-image-marker
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by JimmyDaddy** [comment]
fix it ed2c1993f676968fdbdd0eedc722c6ea5f7757d1
