### ISSUE TITLE
(Android) Cannot read the file from the path

### ISSUE THREAD

**Issue by srichallamalla935** [JimmyDaddy/react-native-image-marker#58]
Actual Behaviour
Android: I am not able to get the file on the path, I am using the latest npm version "^0.6.1",
My path looks like " data/data/com.sampleproject/cache/727b3cdc-2ff1-4918-8a71-f00be535e4d9imagemarker.png"
The cache folder is blank

**Code**

```
  markPosition() {
    //alert(this.state.signature);
    this.state.signature =
      Platform.OS === 'android'
        ? 'file://' + this.state.signature
        : this.state.signature;
    Marker.markText({
      src: this.state.signature,
      text: this.state.data,
      position: 'bottomRight',
      color: '#FF0000',
      fontName: 'Arial-BoldItalicMT',
      fontSize: 44,
      scale: 1,
      quality: 100,
      markerScale: 1,
      shadowStyle: {
        dx: 10.5,
        dy: 20.8,
        radius: 20.9,
        color: 'transparent',
      },
      textBackgroundStyle: {
        paddingX: 10,
        paddingY: 10,
        color: 'transparent',
      },
      saveFormat: 'png',
    })
      .then(path => {
        //  alert('saved path');
        console.log('path1241asdjaksdjakdqweqw', path);
        this.setState(
          {
            signature: path,
          },
          () => {
            if (this.state.signature !== null) {
              //  console.log('dsdsfs4234242', this.state.signature);
              //Orientation.lockToPortrait();
              const getSignatureValue = this.props.navigation.getParam(
                'getSignature',
              );
              getSignatureValue(path);
              // this.props.navigation.push('NALGSample', {
              //   signed: this.state.signature,
              // });
              Orientation.lockToPortrait();
              this.props.navigation.pop();
            }
          },
        );
      })
      .catch(err => {
        console.log('====================================');
        //  alert(err + 'err');
      });
  }
```

**Expected behavior**
 I should able to get the file on the path
My path looks like " data/data/com.sampleproject/cache/727b3cdc-2ff1-4918-8a71-f00be535e4d9imagemarker.png"
The cache folder should not be empty .it should contain the path image

**Versions:**
  "react-native": "0.61.4",
    "react-native-image-marker": "^0.6.1",

**Comment by JimmyDaddy** [comment]
Hello, Android and iOS have a different path format, you can replace
 `getSignatureValue(path);` 
to 
`getSignatureValue(Platform.OS === 'android' ? 'file://' + path : path);`
and try it again.

**Comment by michael-harley** [comment]
> Hello, Android and iOS have a different path format, you can replace
> `getSignatureValue(path);`
> to
> `getSignatureValue(Platform.OS === 'android' ? 'file://' + path : path);`
> and try it again.

I have the same problem, and adding `file://` as the prefix worked for android.

**Comment by yestay90** [comment]
Still having this issue.
