### ISSUE TITLE
makeText saveFormat :'base64' ios  get data crash

### ISSUE THREAD

**Issue by liuhaiqing12** [JimmyDaddy/react-native-image-marker#59]
**Describe the bug**
ImageMarker makeText saveFormat:'base64' ios get base64 data crash

 ImageMarker.markText({
                        src: image.path,
                        text: this.state.locationAddress,
                        position: 'topLeft',
                        color: '#FFFFFF',
                        // fontName: 'Arial-BoldItalicMT',
                        fontSize: 148,
                        scale: 1,
                        quality: 100,
                        saveFormat: 'base64'
                    }).then((res) => {
                        console.log("the path is", res)
                       }).catch((err) => {
                    console.log(err)
                })

Versions:
"react-native": "0.59.5",
"react-native-image-marker": "^0.6.1",

**Comment by JimmyDaddy** [comment]
你好，能贴出具体错误来吗？我这边 demo 跑起来好像都没问题

**Comment by liuhaiqing12** [comment]
没有报错信息，打印返回的base64信息，特别多的信息返回，APP直接无法操作

**Comment by JimmyDaddy** [comment]
那就是图片太大了吧。。。。崩溃应该有错误栈的吧。

**Comment by liuhaiqing12** [comment]
以下是添加文字之前返回的信息
 { exif: null,
  filename: 'IMG_0002.JPG',
  path: '/Users/kk/Library/Developer/CoreSimulator/Devices/DA87FBBE-216A-42E3-8A11-6E14A8C91A98/data/Containers/Data/Application/2C34293E-94C5-4F08-BF12-028F1509BE63/tmp/react-native-image-crop-picker/247289AC-B060-4057-BF33-646BB64E0DAE.jpg',
  height: 2848,
  width: 4288,
  data: null,
  modificationDate: '1441224147',
  localIdentifier: 'B84E8479-475C-4727-A4A4-B77AA9980897/L0/001',
  size: 309786,
  sourceURL: null,
  mime: 'image/jpeg',
  cropRect: null,
  creationDate: '1255122560' }

**Comment by jorgegvallejo** [comment]
I'm getting a crash as well in iOS when using base64.

This is all I get in regards to a stack trace:

```
[...] nil host used in call to allowsSpecificHTTPSCertificateForHost
[...] nil host used in call to allowsAnyHTTPSCertificateForHost:
[...] color? YES
[...] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x18174005c 0x199c5af54 0x181849538 0x1818546b4 0x1816fd474 0x18171be1c 0x102cfd430 0x102cffaa0 0x102efaa44 0x102eff9d0 0x102f00ab8 0x102f014b0 0x104eb4a20 0x104eb6700 0x104eb924c 0x104eca688 0x104ecb08c 0x1f1b75174 0x1f1b74f50)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
terminating with uncaught exception of type NSException```


RN: 0.65.1
react-native-image-marker: 0.6.3
