### ISSUE TITLE
Multiline: textAlign?

### ISSUE THREAD

**Issue by marksturm** [JimmyDaddy/react-native-image-marker#60]
Is there a chance to reach textAlign center on Multilines?

**Comment by marksturm** [comment]
Ok, if i change it to ALIGN_CENTER it works :) on Android.

https://github.com/JimmyDaddy/react-native-image-marker/blob/master/android/src/main/java/com/jimmydaddy/imagemarker/ImageMarkerManager.java#L364

**Comment by yestay90** [comment]
Have you found the solution for text aligning ?

**Comment by JenusDong** [comment]
Now margin only to fill textBackground in Android. We need to be margin horizontally supported.Just like:

int marginHorizontal = 20;
            if (position == null && null != X ) {
                marginHorizontal = X;
            }
            // ALIGN_CENTER, ALIGN_NORMAL, ALIGN_OPPOSITE
            StaticLayout textLayout = new StaticLayout(mark, textPaint, canvas.getWidth() - 2 * marginHorizontal, Layout.Alignment.ALIGN_NORMAL, 1.0f, 0.0f, false);

Hope ASAP to support
