### ISSUE TITLE
MarkerText with Color opacity

### ISSUE THREAD

**Issue by michael-harley** [JimmyDaddy/react-native-image-marker#61]
**Is your feature request related to a problem? Please describe.**
Is there any feature about a transparent text marker, I tried the hexa transparency and rgba, both not working.

**Describe the solution you'd like**
A transparent text marker.

**Comment by yestay90** [comment]
Also want to find way to set background color transparent

**Comment by shubhadeep29** [comment]
How to add alpha/opacity for watermarkTexts, I am using version "1.1.15"
