### ISSUE TITLE
ExceptionsManager.js:74 TypeError: TypeError: Cannot read property 'png' of undefined

### ISSUE THREAD

**Issue by zidniryi** [JimmyDaddy/react-native-image-marker#65]
**Describe the bug**
I've already install different version from this library, and I got same error, cannot read "PNG", and I used the code from example project/

**To Reproduce**
1. Go to Stackoverflow, See The Issue, Change different Library-Version
2. Click on 'and remove dan install node modules'
3. Scroll down to 'This menu'

**Expected behavior**
I want to the library working on react native <60

**Screenshots**
[Image URL](https://lh3.googleusercontent.com/-_QyafhVljYw/XqkIy-LUvkI/AAAAAAAAMUc/gdhwDiAh-2AgM7WXip3uAWTchDy7F66RACK8BGAsYHg/s468/Screen%2BShot%2B2020-04-29%2Bat%2B11.54.37.png)

**Devlopment environment(please complete the following information):**
 - OS: [OSX Catalina]
 - nodejs:  [e.g. 14.9.0]
 - react-native: [e.g. 0.59]
 - react-native-image-marker :  [e.g. 0.51]

**Smartphone (please complete the following information):**
 - Device: [Samsung]
 - OS: [Android 6.0]

**Additional context**
Please give the solution thanks.

**Comment by JimmyDaddy** [comment]
@zidniryi I need more information about your code
