### ISSUE TITLE
Execution failed for task ':react-native-image-marker:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by sachinbasendr** [JimmyDaddy/react-native-image-marker#66]
error: cannot find symbol
            ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this.context).experiment().setMaxBitmapSize(maxSize).build();
                                                                                                  ^
  symbol:   method setMaxBitmapSize(int)
  location: class Builder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-marker:compileReleaseJavaWithJavac'.

**Comment by quangduz** [comment]
```
//ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this.context).experiment().setMaxBitmapSize(maxSize).build();
//Fresco.initialize(this.context, config);
```

Just _**comment**_ this func in ImageMakerManager.java

**Comment by ows-ali** [comment]
@quangduz  This apparently resolves the error and builds successfully but it is not a good practice to modify anything in node_modules. @JimmyDaddy is there any good fix?

**Comment by JimmyDaddy** [comment]
rn verson > 0.6.0 use the latest version of this library while use v0.5.2
https://github.com/JimmyDaddy/react-native-image-marker#installation
