### ISSUE TITLE
How to make the icon image scale dynamic and fit its parent image.

### ISSUE THREAD

**Issue by usama-asfar** [JimmyDaddy/react-native-image-marker#68]
icon image scales differently on different parent image sizes.

marker code 
```js
  ImageMarker.markImage({
        src: path,
        markerSrc: require('../assets/image/category/car.png'),
        position: 'topLeft',
        scale: 1,
        markerScale: 1,
        quality: 100,
      })
        .then((res) => {
          console.log('openLibrary -> res', res);
          setImage('file://' + res);
        })
        .catch((err) => {
          console.log('openLibrary -> err', err);
        });
```

for example, if I'm using an image `height: 340` and `width: 604` 
![20200815_182226 1](https://user-images.githubusercontent.com/42825498/90312770-c8dd8980-df24-11ea-8eb3-a9ae46ea2d10.jpg)

And when I'm using an image `height:  2736` and `width: 3648` 
![20200815_182403 1](https://user-images.githubusercontent.com/42825498/90312788-ed396600-df24-11ea-9358-f0bb1523647d.jpg)

And the second image the icon is very small, how to make the icon differently scale and fits to its parent image.

**Comment by ngocthien0507** [comment]
you can try to create a calculated scale number function base on the image size like :
```javascript
const getScaleNumber = (image: ImageSizeType) => {
  const { width, height } = image
  return (width / 150 + height / 150) / 20  // (1/10)
}

let iconScale = getScaleNumber(imageSize)
```

**Comment by zengqiqing** [comment]
How to calculate this ratio？

**Comment by lijia321** [comment]
How to solve this problem
