### ISSUE TITLE
Can the width and height of the icon be set？

### ISSUE THREAD

**Issue by zengqiqing** [JimmyDaddy/react-native-image-marker#72]
![image](https://user-images.githubusercontent.com/33802481/99933801-05781700-2d97-11eb-9159-42608c5280ab.png)
The image format I use is Base64,now i can only set markerScale, my icons and images are offset。can i set width and height of the icon ?

**Comment by JimmyDaddy** [comment]
你好，是不是你的图片加载组件的样式问题，导致图片展示的时候超出了

**Comment by zengqiqing** [comment]
我想请教一下，能否设定宽高限定水印的大小呢，我上传的图片由于宽高大小都不一，现在会出现水印超出或者水印未能完全覆盖图片的情况。请问我该如何解决这个问题呢？期待您的回复。

下面是我到思否上贴的提问，里面含有我的代码片段：
https://segmentfault.com/q/1010000038256675

**Comment by xclidongbo** [comment]
> 我想请教一下，能否设定宽高限定水印的大小呢，我上传的图片由于宽高大小都不一，现在会出现水印超出或者水印未能完全覆盖图片的情况。请问我该如何解决这个问题呢？期待您的回复。
> 
> 下面是我到思否上贴的提问，里面含有我的代码片段： https://segmentfault.com/q/1010000038256675

解决了吗? 我也在找解决办法.

**Comment by JimmyDaddy** [comment]
use scale instead close by #114
