### ISSUE TITLE
[IOS]Text Stroke at IOS

### ISSUE THREAD

**Issue by IsaacIsrael** [JimmyDaddy/react-native-image-marker#74]
Hey there, I am marking a text into a dark color but in IOS there is a kind of stroke (border) into the text.  Could we please remove or set the stroke color?

**Comment by JimmyDaddy** [comment]
Sorry, it seems normal in iOS at my tests, could you please show me a sample code and screenshot?
<img width="359" alt="截屏2021-09-05 16 06 05" src="https://user-images.githubusercontent.com/16460813/132120032-31c7a6d4-5640-4b19-abfa-f22cc2fbef3c.png">
