### ISSUE TITLE
Font name

### ISSUE THREAD

**Issue by filipef101** [JimmyDaddy/react-native-image-marker#8]
Hello, I dont seem to get font working on android, have you tested that?

**Comment by JimmyDaddy** [comment]
Thanks for reporting this. Did you add the font to your project before you use it?

**Comment by filipef101** [comment]
Typeface typeface = ReactFontManager.getInstance().getTypeface("fonts/" + fontName + ".ttf", 0, this.getReactApplicationContext().getAssets());

             Typeface font = Typeface.createFromAsset(
                     activity.getAssets(), 
                     "fonts/" + fontName + ".ttf");

Yes, i'm using the font with the style on the screen
And I've tried to fix this with the snippets above and other variantions of the path, but i'm new to android native java

**Comment by filipef101** [comment]
@JimmyDaddy 
this solves it                 
    textPaint.setTypeface(ReactFontManager.getInstance().getTypeface(fontName, Typeface.NORMAL, this.getReactApplicationContext().getAssets()) );

I'm modifying my branch of this package so I can't do a PR with this only, maybe this will help someone

**Comment by JimmyDaddy** [comment]
If you forked this repository you can open PR to fix this problem. Thanks

**Comment by filipef101** [comment]
@JimmyDaddy My first PR ;)
