### ISSUE TITLE
rtl text doest work properly

### ISSUE THREAD

**Issue by ansarikhurshid786** [JimmyDaddy/react-native-image-marker#83]
It is really nice library. 

I found only one issue with this. 

Right to left text alway to position right corner. I am trying to align center or but it is going right corner only. 

anyone help me solve this issue?

**Comment by ansarikhurshid786** [comment]
any help

**Comment by JimmyDaddy** [comment]
Hello. Could you please paste your sample code?

**Comment by ansarikhurshid786** [comment]
const options = {
            src: imgOverlay,
            text:"هذا نص عربي",
            position: Position.center,
            color: "#FFFFFF",
            saveFormat: "png",
            fontName: "Arial-BoldItalicMT",
            fontSize: 18,
            scale: 1,
            quality: 100
        };
Marker.markText(options);

**Comment by JimmyDaddy** [comment]
Sorry I didn't reproduce this issue, close temporarily

**Comment by ahmedhango** [comment]
any update ?

**Comment by ansarikhurshid786** [comment]
@ahmedhango use https://www.npmjs.com/package/react-native-photo-manipulator. we just added rtl support, u can se direction property rtl or left.

**Comment by ansarikhurshid786** [comment]
https://github.com/guhungry/react-native-photo-manipulator/issues/943

**Comment by ahmedhango** [comment]
@ansarikhurshid786  thank you for answer :D but 
how to make the text on center when i by x and y here https://github.com/guhungry/react-native-photo-manipulator/issues/943 i need when i type and text be at the center how to get text width to be in the center ?
here in [react-native-image-marker](https://github.com/JimmyDaddy/react-native-image-marker)  they has postion center what about https://github.com/guhungry/react-native-photo-manipulator/issues/943

**Comment by ansarikhurshid786** [comment]
finding center is easy. u can calculate center position of image. 
example: 
const imgHeight = sourceImg.height;
const imgWidth = baseImage.width;

const xCenter = imgWidth/2, yCenter = imgHeight/2;

**Comment by ahmedhango** [comment]
@ansarikhurshid786  okay  and after that how to get  text width to be in the center not start from  center and go right and left you get it ?

**Comment by ansarikhurshid786** [comment]
@ahmedhango which library are u using ?

**Comment by ahmedhango** [comment]
https://github.com/guhungry/react-native-photo-manipulator/issues/943

**Comment by ansarikhurshid786** [comment]
if you are using https://github.com/guhungry/react-native-photo-manipulator/


direction | TextDirection | No | The direction of the text, default to TextDirection.LTR
-- | -- | -- | --


direction	[TextDirection](https://github.com/guhungry/react-native-photo-manipulator/blob/master/README.md#textdirection)	No	The direction of the text, default to TextDirection.LTR

**Comment by ansarikhurshid786** [comment]
u text exactly in center right ?

**Comment by ansarikhurshid786** [comment]
u have to calculate base on width of text then u find

**Comment by guhungry** [comment]
Hi @ansarikhurshid786, @ahmedhango, I am adding text align center here is the result so far in Android

<img width="221" alt="Screenshot 2567-10-26 at 10 51 36" src="https://github.com/user-attachments/assets/eae4a575-1115-423f-881b-95053c46388f">
