### ISSUE TITLE
Allow setting offset with position

### ISSUE THREAD

**Issue by ShivamJoker** [JimmyDaddy/react-native-image-marker#85]
**Is your feature request related to a problem? Please describe.**
I am building a certificate generator where I need to place name in center but I need to move the text a bit upwards.
Right now I will have to calculate the text width and image width and height's as well to just add a bit of offset.  

**Describe the solution you'd like**
It would be great to have params with `offsetX`, `offsetY`

**Describe alternatives you've considered**
Right now I will have to calculate the text width and image width and height's as well to just add a bit of offset.  

**Additional context**

<img width="257" alt="image" src="https://user-images.githubusercontent.com/23727670/146216444-dc3c4a9d-f724-4515-b214-0027122c3e2d.png">

**Comment by ShivamJoker** [comment]
@JimmyDaddy what is the prop for offsetting the text?

**Comment by JimmyDaddy** [comment]
> @JimmyDaddy what is the prop for offsetting the text?

@ShivamJoker You can use `X` or `Y` as shown in the example below
```typescript
await Marker.markText({
    backgroundImage: {...}
    watermarkTexts: [
      {
        text,
        positionOptions: {
//  use percentage to set coordinates
          X: '10%',
          Y: '10%',
        },
        style: {
          ....props
          textBackgroundStyle: {
            type: textBgStretch,
            // use percentage to set paddings
            padding: '10% 10% 10% 10%',
            color: '#00B96B',
          }
        },
      },
    ],
    quality: 100,
    saveFormat: saveFormat,
  });
```
The changes will take effect only after I release a new version.
