### ISSUE TITLE
Cannot read property "addTextbyPostion of null"

### ISSUE THREAD

**Issue by warmgunsutisna** [JimmyDaddy/react-native-image-marker#95]
**Describe the bug**
I have a live production Expo React Native project and am working on a feature to add text watermark to photos online. The error happens when Marker.markText() is called on Expo Go.
Error message reads simply "addTextbyPostion of null"
at Function.markText (index.ts:115:1)
    at ImageViewer.js:45:1
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at asyncToGenerator.js:27:1
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:1
    at transformImage (ImageViewer.js:42:1)
    at ImageViewer.js:89:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at commitRootImpl (react-dom.development.js:26935:1)
    at commitRoot (react-dom.development.js:26682:1)
    at performSyncWorkOnRoot (react-dom.development.js:26117:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at react-dom.development.js:25651:1
![image marker expo error](https://user-images.githubusercontent.com/124228777/230567007-a799c4fa-2a95-4147-8f30-b7f5db07dd7d.jpeg)

**To Reproduce**
1. Create an Expo project and call the method from useEffect hook
2. Using try catch, the error.message is printed and also logged to my Sentry account

**Expected behavior**
Watermark created on the picture, producing a new Base64 Uri that could be displayed on the app

**Screenshots**
Included 

**Devlopment environment(please complete the following information):**
 - OS: Windows 7 Ultimate Service Pack 1 64 bit with Visual Studio Code 
 - nodejs:  14.17.0

package.json:
 "dependencies": {
    "@expo/webpack-config": "^18.0.1",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/material-bottom-tabs": "^6.2.12",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/stack": "^6.3.12",
    "@reduxjs/toolkit": "^1.9.2",
    "@sentry/react-native": "4.13.0",
    "axios": "^1.3.3",
    "expo": "^48.0.8",
    "expo-application": "~5.1.1",
    "expo-camera": "~13.2.1",
    "expo-clipboard": "~4.1.2",
    "expo-constants": "~14.2.1",
    "expo-device": "~5.2.1",
    "expo-file-system": "~15.2.2",
    "expo-image-picker": "~14.1.1",
    "expo-modules-core": "~1.2.5",
    "expo-navigation-bar": "~2.1.1",
    "expo-sharing": "~11.2.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.71.6",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-global-props": "^1.1.5",
    "react-native-image-marker": "^0.6.3",
    "react-native-image-slider-banner": "^1.0.3",
    "react-native-paper": "^5.1.4",
    "react-native-radio-buttons-group": "^2.3.1",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "^0.18.12",
    "react-native-webview": "11.26.0",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "redux-thunk": "^2.4.2",
    "sentry-expo": "~6.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "eslint-plugin-react-hooks": "^4.6.0"
  },
  "private": true,
  "resolutions": {
    "@expo/config-plugins": "^6.0.0"
  }

**Smartphone (please complete the following information):**
 - Device: Redmi 9A
 - OS: Android 10
 - Expo Go 2.28.6 SDKs 46, 47, 48

**Additional context**
N/A

**Comment by JimmyDaddy** [comment]
pls use the latest version try again
